"""Referencias bibliográficas y distinciones filosóficas.

Solo se incluyen datos bibliográficos comprobables. Cuando no hay un año o una
ubicación precisa confirmada, el campo se deja vacío en lugar de inventarlo.
"""


def ref(rid, authors, year, title, container="", locator=""):
    return {"id": rid, "authors": authors, "year": year, "title": title,
            "container": container, "locator": locator, "verified": True}


SEP = "Stanford Encyclopedia of Philosophy (entrada en línea)"

REFERENCES = [
    ref("ref_williams_1976", "Bernard Williams", "1976", "Moral Luck",
        "Proceedings of the Aristotelian Society, vol. supl. 50; reimpreso en Moral Luck, Cambridge University Press, 1981"),
    ref("ref_nagel_1976", "Thomas Nagel", "1976", "Moral Luck",
        "Proceedings of the Aristotelian Society, vol. supl. 50; reimpreso en Mortal Questions, Cambridge University Press, 1979"),
    ref("ref_waldron_1995", "Jeremy Waldron", "1995", "Moments of Carelessness and Massive Loss",
        "en D. Owen (ed.), Philosophical Foundations of Tort Law, Oxford University Press"),
    ref("ref_kant_fundamentacion", "Immanuel Kant", "1785", "Fundamentación de la metafísica de las costumbres"),
    ref("ref_sep_moral_luck", "Dana K. Nelkin", "", "Moral Luck", SEP),
    ref("ref_ross_1930", "W. D. Ross", "1930", "The Right and the Good", "Oxford University Press"),
    ref("ref_hume_tratado", "David Hume", "1739–1740", "Tratado de la naturaleza humana", "",
        "libro 3, parte 2, sección 5"),
    ref("ref_scanlon_1998", "T. M. Scanlon", "1998", "What We Owe to Each Other", "Harvard University Press"),
    ref("ref_sep_promises", "Allen Habib", "", "Promises", SEP),
    ref("ref_platon_eutifron", "Platón", "", "Eutifrón"),
    ref("ref_analectas", "Tradición confuciana", "", "Analectas", "", "13.18"),
    ref("ref_mencio", "Mencio", "", "Mencio", "", "7A35"),
    ref("ref_godwin_1793", "William Godwin", "1793", "An Enquiry Concerning Political Justice"),
    ref("ref_williams_pcm", "Bernard Williams", "1976", "Persons, Character and Morality",
        "en A. O. Rorty (ed.), The Identities of Persons; reimpreso en Moral Luck, 1981"),
    ref("ref_noddings_1984", "Nel Noddings", "1984", "Caring: A Feminine Approach to Ethics and Moral Education",
        "University of California Press"),
    ref("ref_agustin_mendacio", "Agustín de Hipona", "c. 395", "Sobre la mentira (De mendacio)"),
    ref("ref_kant_1797", "Immanuel Kant", "1797", "Sobre un presunto derecho a mentir por filantropía",
        "respuesta a Benjamin Constant"),
    ref("ref_korsgaard_1986", "Christine M. Korsgaard", "1986", "The Right to Lie: Kant on Dealing with Evil",
        "Philosophy & Public Affairs 15(4)"),
    ref("ref_bok_1978", "Sissela Bok", "1978", "Lying: Moral Choice in Public and Private Life", "Pantheon Books"),
    ref("ref_williams_2002", "Bernard Williams", "2002", "Truth and Truthfulness", "Princeton University Press"),
    ref("ref_saul_2012", "Jennifer M. Saul", "2012", "Lying, Misleading, and What Is Said", "Oxford University Press"),
    ref("ref_sep_deontology", "Larry Alexander y Michael Moore", "", "Deontological Ethics", SEP),
    ref("ref_kleinberg_2016", "Jon Kleinberg, Sendhil Mullainathan y Manish Raghavan", "2016",
        "Inherent Trade-Offs in the Fair Determination of Risk Scores", "arXiv:1609.05807"),
    ref("ref_chouldechova_2017", "Alexandra Chouldechova", "2017",
        "Fair Prediction with Disparate Impact: A Study of Bias in Recidivism Prediction Instruments", "Big Data 5(2)"),
    ref("ref_angwin_2016", "Julia Angwin, Jeff Larson, Surya Mattu y Lauren Kirchner", "2016", "Machine Bias",
        "ProPublica"),
    ref("ref_dieterich_2016", "William Dieterich, Christina Mendoza y Tim Brennan", "2016",
        "COMPAS Risk Scales: Demonstrating Accuracy Equity and Predictive Parity", "Northpointe"),
    ref("ref_hellman_2020", "Deborah Hellman", "2020", "Measuring Algorithmic Fairness", "Virginia Law Review 106"),
    ref("ref_rawls_1971", "John Rawls", "1971", "A Theory of Justice", "Harvard University Press"),
    ref("ref_rachels_1975", "James Rachels", "1975", "Why Privacy Is Important", "Philosophy & Public Affairs 4(4)"),
    ref("ref_solove_2007", "Daniel J. Solove", "2007",
        "'I've Got Nothing to Hide' and Other Misunderstandings of Privacy", "San Diego Law Review 44"),
    ref("ref_nissenbaum_2004", "Helen Nissenbaum", "2004", "Privacy as Contextual Integrity", "Washington Law Review 79"),
    ref("ref_nissenbaum_2010", "Helen Nissenbaum", "2010", "Privacy in Context", "Stanford University Press"),
    ref("ref_mill_1859", "John Stuart Mill", "1859", "Sobre la libertad"),
    ref("ref_feinberg_1986", "Joel Feinberg", "1986", "Harm to Self", "Oxford University Press"),
    ref("ref_turing_1950", "Alan M. Turing", "1950", "Computing Machinery and Intelligence", "Mind 59"),
    ref("ref_searle_1980", "John R. Searle", "1980", "Minds, Brains, and Programs", "Behavioral and Brain Sciences 3(3)"),
    ref("ref_dennett_1987", "Daniel C. Dennett", "1987", "The Intentional Stance", "MIT Press"),
    ref("ref_bender_koller_2020", "Emily M. Bender y Alexander Koller", "2020",
        "Climbing towards NLU: On Meaning, Form, and Understanding in the Age of Data", "Proceedings of ACL 2020"),
    ref("ref_sep_chinese_room", "David Cole", "", "The Chinese Room Argument", SEP),
    ref("ref_locke_ensayo", "John Locke", "1694", "Ensayo sobre el entendimiento humano (2.ª edición)", "",
        "libro II, capítulo 27"),
    ref("ref_reid_1785", "Thomas Reid", "1785", "Essays on the Intellectual Powers of Man", "", "ensayo III, capítulo 6"),
    ref("ref_williams_1970", "Bernard Williams", "1970", "The Self and the Future", "The Philosophical Review 79(2)"),
    ref("ref_parfit_1984", "Derek Parfit", "1984", "Reasons and Persons", "Oxford University Press", "parte III"),
    ref("ref_olson_1997", "Eric T. Olson", "1997", "The Human Animal: Personal Identity Without Psychology",
        "Oxford University Press"),
    ref("ref_milindapanha", "Tradición budista", "", "Milindapañha (Las preguntas de Milinda)"),
    ref("ref_nagel_1974", "Thomas Nagel", "1974", "What Is It Like to Be a Bat?", "The Philosophical Review 83(4)"),
    ref("ref_jackson_1982", "Frank Jackson", "1982", "Epiphenomenal Qualia", "The Philosophical Quarterly 32"),
    ref("ref_paul_2014", "L. A. Paul", "2014", "Transformative Experience", "Oxford University Press"),
    ref("ref_fricker_2007", "Miranda Fricker", "2007", "Epistemic Injustice: Power and the Ethics of Knowing",
        "Oxford University Press"),
    ref("ref_nussbaum_1995", "Martha C. Nussbaum", "1995", "Poetic Justice: The Literary Imagination and Public Life",
        "Beacon Press"),
    ref("ref_russell_1911", "Bertrand Russell", "1910–1911", "Knowledge by Acquaintance and Knowledge by Description",
        "Proceedings of the Aristotelian Society 11"),
]


def dist(did, name, short, relation, debate, objection, refs,
         opening="Otras personas también pensaron en esta diferencia."):
    return {"id": did, "everydayName": name, "shortExplanation": short,
            "philosophicalRelation": relation, "openingLine": opening,
            "debateAuthors": debate, "mainObjection": objection, "referenceIds": refs}


DISTINCTIONS = [
    dist("d01_reproche_reparacion", "Culpa y reparación",
         "No es lo mismo merecer reproche que tener que reparar un daño.",
         "la suerte moral y la responsabilidad por los resultados",
         "El problema fue planteado por Bernard Williams y Thomas Nagel en 1976. Jeremy Waldron lo analizó al pensar cómo repartir las cargas cuando dos descuidos iguales tienen consecuencias muy distintas (1995).",
         "Si el reproche no depende del resultado, ¿por qué sentimos que quien causó un daño grave debe algo más que una disculpa?",
         ["ref_waldron_1995", "ref_williams_1976", "ref_nagel_1976", "ref_sep_moral_luck"],
         "Esta diferencia se discute desde hace mucho."),
    dist("d02_cargar_con_lo_hecho", "Cargar con lo que hiciste",
         "Se puede sentir el peso de lo ocurrido sin haber sido peor persona que otro.",
         "el llamado arrepentimiento del agente",
         "Bernard Williams (1976) describió este sentimiento propio de quien causó algo, distinto de la culpa por una falta.",
         "¿Es razonable sentir un peso que no corresponde a ninguna falta propia?",
         ["ref_williams_1976", "ref_sep_moral_luck"]),
    dist("d03_deber_que_pesa", "Un deber que pesa y un deber que decide",
         "Un deber puede tener peso real y aun así ceder ante otro más fuerte en un caso concreto.",
         "los deberes prima facie",
         "W. D. Ross (1930) distinguió los deberes que pesan de antemano del deber que, considerado todo, decide en cada situación.",
         "Si todo deber puede ceder, ¿cómo saber cuál pesa más sin una regla para compararlos?",
         ["ref_ross_1930"], "Esta diferencia se discute desde hace mucho."),
    dist("d04_decepcionar_faltar", "Decepcionar y faltar a la palabra",
         "Romper una promesa puede ser incorrecto aunque la otra persona nunca se entere.",
         "la naturaleza de la obligación que crea una promesa",
         "David Hume vio las promesas como una convención social útil. T. M. Scanlon las explica por lo que le debemos a quien confió en nosotros.",
         "Si nadie resulta decepcionado, ¿dónde está exactamente el daño?",
         ["ref_hume_tratado", "ref_scanlon_1998", "ref_sep_promises"]),
    dist("d05_nuestros_todos", "Lo que debemos a los nuestros y lo que debemos a todos",
         "Hay deberes especiales con quienes queremos que no tenemos con todos.",
         "el debate entre parcialidad e imparcialidad",
         "William Godwin defendió una imparcialidad estricta (1793). Bernard Williams criticó exigirla con quienes amamos. El Eutifrón de Platón, las Analectas (13.18) y el Mencio (7A35) muestran el mismo conflicto entre familia y justicia.",
         "Si los deberes especiales pesan tanto, ¿qué impide que la lealtad se vuelva injusticia con los demás?",
         ["ref_godwin_1793", "ref_williams_pcm", "ref_platon_eutifron", "ref_analectas", "ref_mencio"],
         "Esta diferencia se discute desde hace siglos, en tradiciones muy distintas."),
    dist("d06_mentir_no_decir", "Mentir y no decirlo todo",
         "Decir algo falso no es lo mismo que callar o elegir con cuidado qué decir.",
         "la distinción entre mentir e inducir a error sin mentir",
         "Jennifer Saul (2012) y Bernard Williams (2002) discuten si mentir es peor que engañar con palabras verdaderas. Sissela Bok (1978) estudió la mentira en la vida cotidiana.",
         "Si el efecto en la otra persona es el mismo, ¿importa que la frase haya sido literalmente verdadera?",
         ["ref_saul_2012", "ref_williams_2002", "ref_bok_1978"]),
    dist("d07_linea_fija_movil", "Una línea fija o una línea que se mueve",
         "Algunos límites no se cruzan nunca; otros ceden cuando lo que está en juego es muy grave.",
         "la deontología absoluta y la deontología de umbral",
         "Kant sostuvo que no se debe mentir ni siquiera a quien busca hacer daño (1797). Christine Korsgaard reexaminó ese caso (1986). La idea de un umbral aparece en la discusión contemporánea sobre la ética deontológica.",
         "Si la línea se mueve, ¿qué la distingue de simplemente calcular consecuencias?",
         ["ref_kant_1797", "ref_korsgaard_1986", "ref_sep_deontology"]),
    dist("d08_puntaje_errores", "Que una beca signifique lo mismo, o que los errores se repartan igual",
         "Son dos ideas razonables de justicia y, cuando los grupos son distintos, no siempre pueden cumplirse a la vez.",
         "los criterios de equidad en las decisiones automáticas",
         "Alexandra Chouldechova (2017) y Kleinberg, Mullainathan y Raghavan (2016) mostraron que, si los grupos tienen tasas distintas y la predicción no es perfecta, no se pueden cumplir todos los criterios a la vez. El caso COMPAS enfrentó a ProPublica y Northpointe por esta razón. Deborah Hellman (2020) analizó qué criterio importa moralmente.",
         "Si ningún criterio puede cumplirse del todo, ¿quién decide cuál sacrificar y con qué legitimidad?",
         ["ref_chouldechova_2017", "ref_kleinberg_2016", "ref_angwin_2016", "ref_dieterich_2016", "ref_hellman_2020"],
         "Esta diferencia se discute desde hace pocos años, y ya es central."),
    dist("d09_ocultar_contexto", "Ocultar algo o sacarlo de su lugar",
         "La privacidad no protege solo secretos: protege que la información llegue a quien corresponde y para lo que corresponde.",
         "la integridad contextual",
         "Helen Nissenbaum (2004, 2010) propuso juzgar cada flujo de información según las normas de su contexto. James Rachels (1975) vinculó la privacidad con la posibilidad de tener relaciones distintas con personas distintas. Daniel Solove (2007) analizó el argumento de no tener nada que ocultar.",
         "Si todo depende del contexto, ¿quién fija las normas de cada contexto?",
         ["ref_nissenbaum_2004", "ref_nissenbaum_2010", "ref_rachels_1975", "ref_solove_2007"]),
    dist("d10_usar_entender", "Usar bien las palabras y entenderlas",
         "Manejar símbolos con acierto no es necesariamente saber lo que significan.",
         "la diferencia entre sintaxis y semántica",
         "John Searle (1980) la defendió con el argumento de la habitación china. Alan Turing (1950) propuso juzgar la inteligencia por la conducta. Daniel Dennett (1987) defendió atribuir estados mentales cuando eso ayuda a entender y predecir.",
         "Si solo vemos la conducta de los demás, ¿con qué criterio negamos comprensión a una máquina y se la concedemos a una persona?",
         ["ref_searle_1980", "ref_turing_1950", "ref_dennett_1987", "ref_bender_koller_2020", "ref_sep_chinese_room"]),
    dist("d11_seguir_conservar", "Seguir siendo tú o conservar lo que te importa",
         "Quizás lo decisivo no es si hay identidad, sino si continúa lo que valoras.",
         "el debate sobre la identidad personal",
         "Locke ligó la identidad personal a la conciencia y la memoria. Thomas Reid le objetó casos de memoria interrumpida. Derek Parfit (1984) sostuvo que la identidad no es lo que importa.",
         "Si la identidad no importa, ¿por qué nos preocupa tanto lo que le pasará a nuestro yo futuro?",
         ["ref_locke_ensayo", "ref_reid_1785", "ref_parfit_1984", "ref_williams_1970"],
         "Esta diferencia se discute desde hace siglos."),
    dist("d12_saber_vivido", "Saber sobre algo y haberlo vivido",
         "Se pueden comprender las razones de alguien sin saber cómo se siente vivirlas.",
         "el conocimiento por familiaridad y el conocimiento por descripción",
         "Bertrand Russell (1910–1911) distinguió ambos tipos de conocimiento. Thomas Nagel (1974) y Frank Jackson (1982) defendieron que hay algo de la experiencia que no se capta desde fuera. L. A. Paul (2014) lo aplicó a las decisiones que nos transforman.",
         "Si nadie puede comprender lo que no vivió, ¿cómo podríamos resolver desacuerdos entre personas con vidas distintas?",
         ["ref_russell_1911", "ref_nagel_1974", "ref_jackson_1982", "ref_paul_2014", "ref_fricker_2007"]),
]
