from common import *

E1 = "e1_mismo_descuido"
E2 = "e2_promesa_sabado"
E3 = "e3_lo_que_viste"

# ---------------------------------------------------------------- E1
e1 = {
    "id": E1, "order": 1, "tramo": 1,
    "title": "El mismo descuido",
    "question": "¿Importa más lo que decidiste hacer o lo que ocurrió?",
    "sensitive": True,
    "sensitiveNote": "Esta pregunta menciona un accidente en el que un niño resulta herido.",
    "scenario": {
        "layout": "twin",
        "paragraphs": ["Dos personas hacen exactamente lo mismo. Solo cambia lo que pasa después."],
        "twin": [
            {"name": "Ana", "lines": ["Mira el celular tres segundos mientras maneja.",
                                      "Misma calle, misma velocidad.",
                                      "No pasa nada."]},
            {"name": "Beto", "lines": ["Mira el celular tres segundos mientras maneja.",
                                       "Misma calle, misma velocidad.",
                                       "Un niño cruza. Beto no alcanza a frenar y el niño queda herido."]},
        ],
    },
    "probes": [{
        "id": "e1_gemelos", "type": "twinCases", "placement": "elige",
        "prompt": "Primera impresión: ¿cuánto reproche merece cada uno?",
        "config": {"subjects": [{"id": "ana", "label": "Ana"}, {"id": "beto", "label": "Beto"}],
                   "scale": ["Nada", "Poco", "Algo", "Bastante", "Mucho"]},
    }],
    "judgment": {"prompt": "¿Merecen el mismo reproche?",
                 "left": {"label": "Merecen el mismo reproche", "short": "El mismo"},
                 "right": {"label": "Beto merece más reproche", "short": "Beto, más"}},
    "reasons": [
        reason("e1_r_decision", "Importa lo que cada uno decidió hacer", ["p_decision"], "left"),
        reason("e1_r_riesgo", "Importa el riesgo que cada uno tomó", ["p_riesgo"], "left"),
        reason("e1_r_resultado", "Importa lo que terminó pasando", ["p_resultado"], "right"),
        reason("e1_r_victima", "Un niño herido lo cambia todo", ["p_resultado"], "right"),
    ],
    "triggers": [
        trig("e1_t_impresion", 5, "internal", "e1_q_impresion",
             all_(leaf("this.probe.e1_gemelos.diff", "gt", 0), leaf("this.stance.initial", "lte", 0))),
        trig("e1_t_misma_decision", 10, "twin", "e1_q_misma_decision",
             all_(leaf("this.stance.initial", "gt", 0),
                  leaf("this.reason.id", "in", ["e1_r_decision", "e1_r_riesgo"]))),
        trig("e1_t_diez_segundos", 11, "twin", "e1_q_diez_segundos",
             all_(leaf("this.stance.initial", "gt", 0),
                  leaf("this.reason.id", "in", ["e1_r_resultado", "e1_r_victima"]))),
        trig("e1_t_sancion", 12, "twin", "e1_q_sancion", leaf("this.stance.initial", "lt", 0)),
        trig("e1_t_inclinarte", 13, "internal", "e1_q_inclinarte", leaf("this.stance.initial", "eq", 0)),
        trig("e1_t_misma_decision_b", 14, "twin", "e1_q_misma_decision_b", leaf("this.stance.initial", "gt", 0)),
    ],
    "questions": [
        clarification("e1_q_impresion",
                      "En tu primera impresión, Beto merecía más reproche que Ana. En tu postura, no. ¿Qué cambió?",
                      [ans("pense", "Lo pensé mejor", "e1_q_sancion", leaf("this.stance.initial", "lt", 0)),
                       ans("reaccion", "Mi primera reacción no es mi juicio", "e1_q_sancion",
                           leaf("this.stance.initial", "lt", 0)),
                       ans("otra", "Otra cosa")]),
        tension("e1_q_misma_decision",
                "Elegiste «{esta_razon}». Ana y Beto decidieron exactamente lo mismo, pero juzgas distinto a Beto. Hay algo interesante aquí.",
                "Entonces, si tu razón se sostiene, Ana y Beto deberían recibir el mismo reproche. ¿Lo aceptas?"),
        tension("e1_q_misma_decision_b",
                "Ana y Beto decidieron exactamente lo mismo, pero juzgas distinto a Beto. Hay algo interesante aquí.",
                "Entonces, lo que decidieron no alcanza para explicar tu juicio. ¿Lo aceptas?"),
        tension("e1_q_diez_segundos",
                "Elegiste «{esta_razon}». Imagina que Ana hubiera mirado el celular diez segundos y aun así no pasara nada. ¿Merecería menos reproche que Beto, que miró tres?",
                "Entonces, alguien más imprudente podría merecer menos reproche solo porque tuvo suerte. ¿Lo aceptas?"),
        tension("e1_q_sancion",
                "Si el reproche es igual, ¿deberían recibir la misma sanción? ¿Beto debería pagar el tratamiento del niño y Ana no pagar nada?",
                "Entonces, Ana debería responder igual que Beto ante la familia del niño. ¿Lo aceptas?"),
        clarification("e1_q_inclinarte", "¿Qué necesitarías saber para inclinarte hacia un lado?",
                      [ans("frenar", "Si Beto pudo frenar a tiempo"),
                       ans("primera", "Si era la primera vez que lo hacían"),
                       ans("nada", "Nada: los dos lados pesan igual")]),
    ],
    "differences": [
        diff("e1_dif_reparar", "Una cosa es cuánto se le reprocha y otra quién repara el daño",
             "d01_reproche_reparacion",
             "Si esa diferencia importa, Ana y Beto merecen el mismo reproche, pero solo Beto debe reparar el daño. ¿Lo sostienes?"),
        diff("e1_dif_cargar", "Beto carga con lo que pasó, aunque no sea peor persona",
             "d02_cargar_con_lo_hecho",
             "Si esa diferencia importa, Beto puede sentir un peso que Ana no siente, sin ser peor que ella. ¿Lo sostienes?"),
        diff("e1_dif_castigo", "Castigar distinto puede servir para otras cosas, como proteger a otros",
             None,
             "Si esa diferencia importa, la sanción puede ser distinta aunque el reproche sea el mismo. ¿Lo sostienes?"),
    ],
    "cruza": {
        "left": side("e1_l",
            ["Juzgar por lo que nadie controla es juzgar a la suerte",
             "Cada persona responde por lo que decide"],
            ["Ana y Beto tomaron la misma decisión, en la misma calle",
             "Que el niño cruzara en ese instante no dependió de Beto"],
            "Merecen el mismo reproche, aunque solo Beto deba reparar el daño",
            [(["e1_r_resultado", "e1_r_victima"],
              "Pasó algo terrible, y por eso Beto debe reparar. Pero reparar no es lo mismo que ser peor persona.")],
            "Lo que ocurrió importa para reparar, no para decidir quién fue más imprudente.",
            [("malaIntencion", "Les da igual el niño herido",
              "Quien sostiene esta postura no minimiza el daño: separa el daño del reproche."),
             ("exageracion", "Nadie es responsable de nada",
              "No niegan la responsabilidad: dicen que Ana y Beto son igual de responsables."),
             ("versionDebil", "Total, todos miramos el celular alguna vez",
              "No lo justifican por costumbre: lo juzgan igual de grave en los dos casos.")],
            "Lo único que cuenta es lo que ocurrió",
            [voice("e1_l_v1", "Perspectiva de quien maneja a diario",
                   "Eso no es lo que pienso: esa idea es del otro lado.",
                   "Vas bien, pero falta lo que más me importa.",
                   "Sí, así lo diría: juzgo lo que cada uno decidió.",
                   "Lo dijiste mejor que yo: reproche igual, reparación aparte."),
             voice("e1_l_v2", "Perspectiva de quien evalúa accidentes de tránsito",
                   "No me representa: así no razono los casos.",
                   "Hay algo, pero falta por qué aplica a este caso.",
                   "Así lo diría: la decisión fue la misma.",
                   "Muy bien construido: separaste culpa y reparación."),
             voice("e1_l_v3", "Perspectiva de quien vivió un casi accidente",
                   "Eso no es lo que siento ni lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí: yo pude ser Beto, y no por eso fui mejor.",
                   "Así mismo. Entendiste por qué no me siento mejor que Beto.")]),
        "right": side("e1_r",
            ["Lo que hacemos incluye lo que causamos",
             "Las disculpas y las reparaciones responden a lo que ocurrió"],
            ["Beto hirió a un niño; Ana no hirió a nadie",
             "Muchos sistemas penales distinguen un daño consumado de uno que no ocurrió"],
            "Beto merece más reproche que Ana",
            [(["e1_r_decision"],
              "Decidieron lo mismo, sí. Pero el reproche también responde a lo que pasó en el mundo, no solo en la cabeza."),
             (["e1_r_riesgo"], "El riesgo fue igual; el daño no. Y el daño también cuenta.")],
            "Nadie vive solo de intenciones: lo ocurrido forma parte de lo que hicimos.",
            [("malaIntencion", "Solo quieren un culpable",
              "No buscan un culpable: dicen que el daño real cambia lo que Beto hizo."),
             ("exageracion", "Si no pasa nada, puedes hacer lo que quieras",
              "No aprueban lo que hizo Ana: dicen que Beto hizo algo más."),
             ("versionDebil", "Beto tuvo mala suerte, que se aguante",
              "No es desprecio por Beto: es tomar en serio lo que le pasó al niño.")],
            "Solo importa lo que cada uno decidió",
            [voice("e1_r_v1", "Perspectiva de quien tiene un familiar herido en la calle",
                   "Eso no es lo que pienso: suena a la otra postura.",
                   "Algo hay, pero falta lo que más nos importa.",
                   "Sí, así lo diría: el daño fue real.",
                   "Especialmente fuerte: respondiste a lo que el otro lado diría."),
             voice("e1_r_v2", "Perspectiva de quien trabaja en justicia",
                   "No me representa.",
                   "Parcialmente. Falta la conexión con este caso.",
                   "Así lo diría: el resultado forma parte del acto.",
                   "Muy bien: incluiste cómo responderíamos a tu razón."),
             voice("e1_r_v3", "Perspectiva de quien cruza esa calle a diario",
                   "Eso no es lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí: el niño herido cambia lo que Beto hizo.",
                   "Así mismo, y dicho con respeto por los dos.")]),
    },
    "twist": {"text": "Muchos sistemas penales castigan distinto un daño consumado que uno que no llegó a ocurrir, aunque la conducta haya sido la misma. ¿Cambia algo en tu postura?"},
    "reflection": "Si la suerte decide tanto de lo que hacemos, ¿qué parte de lo que hacemos es realmente nuestra?",
    "map": [{"axis": "ax_intencion_resultado", "source": "stance", "polarity": 1}],
    "deepDive": {
        "problem": "El problema de la suerte moral. Solemos pensar que solo merecemos juicio por lo que controlamos, pero en la práctica también juzgamos por lo que ocurre, y lo que ocurre depende en parte de la suerte.",
        "positions": ["El reproche depende solo de lo que cada persona decidió y controló.",
                      "Lo que hacemos incluye lo que causamos, aunque no lo controlemos del todo."],
        "traditions": "Bernard Williams y Thomas Nagel plantearon el problema en 1976. Kant sostuvo que el valor moral de una acción está en la buena voluntad y no en sus efectos. Jeremy Waldron discutió cómo repartir las cargas cuando dos descuidos iguales tienen consecuencias distintas.",
        "objection": "Nagel mostró que, si se aplica con rigor la idea de juzgar solo lo que controlamos, casi nada queda libre de la suerte: ni las circunstancias, ni el carácter, ni los resultados.",
        "references": ["ref_williams_1976", "ref_nagel_1976", "ref_waldron_1995", "ref_kant_fundamentacion",
                       "ref_sep_moral_luck"],
    },
}

# ---------------------------------------------------------------- E2
e2 = {
    "id": E2, "order": 2, "tramo": 1,
    "title": "La promesa del sábado",
    "question": "¿Cuándo es legítimo romper una promesa?",
    "sensitive": False,
    "scenario": {"layout": "single", "paragraphs": [
        "Le prometiste a tu hermana de 12 años que irías el sábado a su presentación de danza. Nadie más de la familia puede ir.",
        "El viernes te ofrecen un turno extra muy bien pagado que cubriría una deuda urgente de tu familia. Solo puede ser ese sábado."]},
    "probes": [{
        "id": "e2_secreto", "type": "choiceVariant", "placement": "vuelve",
        "prompt": "Imagina que ella nunca se enteraría: creería que llegaste tarde y te fuiste pronto.",
        "config": {"options": [{"id": "falle", "label": "Sigue estando mal: falté a mi palabra"},
                               {"id": "cambia", "label": "Cambia: si no la decepciono, no hay daño"},
                               {"id": "nose", "label": "No lo sé"}]},
    }],
    "judgment": {"prompt": "¿Qué harías?",
                 "left": {"label": "Cumplir la promesa", "short": "Cumplir"},
                 "right": {"label": "Romperla, explicándolo", "short": "Romperla"}},
    "reasons": [
        reason("e2_r_palabra", "Una promesa se cumple aunque cueste", ["p_palabra"], "left"),
        reason("e2_r_hermana", "Ella cuenta conmigo y nadie más irá", ["p_cuidado"], "left"),
        reason("e2_r_deuda", "La deuda afecta a toda la familia", ["p_mejor_resultado"], "right"),
        reason("e2_r_liberar", "Puedo pedirle que me libere y reparar", ["p_mejor_resultado"], "right"),
    ],
    "triggers": [
        trig("e2_t_mem_decision", 1, "memory", "e2_q_mem_decision",
             all_(leaf("e1_mismo_descuido.reason.id", "in", ["e1_r_decision", "e1_r_riesgo"]),
                  leaf("this.stance.initial", "gt", 0)), memory=E1),
        trig("e2_t_mem_resultado", 2, "memory", "e2_q_mem_resultado",
             all_(leaf("e1_mismo_descuido.reason.id", "in", ["e1_r_resultado", "e1_r_victima"]),
                  leaf("this.stance.initial", "lt", 0)), memory=E1),
        trig("e2_t_liberar", 10, "assumption", "e2_q_liberar", leaf("this.stance.initial", "lt", 0)),
        trig("e2_t_unica", 11, "assumption", "e2_q_unica", leaf("this.stance.initial", "gt", 0)),
        trig("e2_t_centro", 12, "internal", "e2_q_centro", leaf("this.stance.initial", "eq", 0)),
    ],
    "questions": [
        tension("e2_q_mem_decision",
                "En «{titulo}» elegiste «{razon}». Aquí romperías la promesa por una buena razón. ¿Alcanza la buena intención si ella igual se queda esperando?",
                "Entonces, lo que decidiste importa más que lo que ella vive ese sábado. ¿Lo aceptas?"),
        tension("e2_q_mem_resultado",
                "En «{titulo}» elegiste «{razon}». Aquí cumplir la promesa trae un peor resultado para tu familia. ¿Cómo lo ves?",
                "Entonces, en este caso, la palabra dada pesa más que el resultado. ¿Lo aceptas?"),
        assumption("e2_q_liberar",
                   "Tu razón supone que una promesa obliga aunque ella pudiera liberarte si se lo pidieras. ¿Lo crees?",
                   "e2_q_liberar_b"),
        tension("e2_q_liberar_b",
                "Si ella pudiera liberarte, la promesa quizá no obliga del todo. ¿Qué hacemos con eso?",
                "Entonces, una promesa obliga incluso cuando la otra persona podría liberarte. ¿Lo aceptas?"),
        assumption("e2_q_unica",
                   "Tu razón supone que el turno extra es la única forma de cubrir la deuda. ¿Lo crees?"),
        clarification("e2_q_centro", "¿Qué haría que te inclinaras hacia un lado?",
                      [ans("hablar", "Poder hablarlo antes con ella"),
                       ans("monto", "Saber cuánto pesa la deuda"),
                       ans("nada", "Nada: las dos cosas pesan igual")]),
    ],
    "differences": [
        diff("e2_dif_pesa", "Un deber puede pesar sin ser el que decide", "d03_deber_que_pesa",
             "Si esa diferencia importa, la promesa sigue pesando aunque decidas romperla, y algo quedas debiendo. ¿Lo sostienes?"),
        diff("e2_dif_decepcion", "Decepcionarla no es lo mismo que faltar a mi palabra", "d04_decepcionar_faltar",
             "Si esa diferencia importa, romper la promesa estaría mal incluso si ella nunca se enterara. ¿Lo sostienes?"),
        diff("e2_dif_liberar", "Si ella me libera, ya no la rompo", "d04_decepcionar_faltar",
             "Si esa diferencia importa, lo decisivo es su acuerdo, no el resultado. ¿Lo sostienes?"),
    ],
    "cruza": {
        "left": side("e2_l",
            ["Una promesa crea una confianza que antes no existía",
             "Una promesa que se rompe cuando conviene deja de ser una promesa"],
            ["Ella organizó su día contando con tu palabra", "Nadie más de la familia irá a verla"],
            "Hay que cumplir y buscar otra salida para la deuda",
            [(["e2_r_deuda"], "La deuda importa, pero hay otras formas de cubrirla. No hay otra forma de estar en su presentación."),
             (["e2_r_liberar"], "Pedirle a una niña de 12 años que te libere es ponerla en un aprieto, no darle una elección.")],
            "Una promesa también protege la confianza de quien espera.",
            [("malaIntencion", "Solo quieren quedar bien",
              "No se trata de imagen: se trata de lo que la hermana espera."),
             ("exageracion", "Hay que cumplir aunque se hunda la familia",
              "No dicen que la familia no importe: dicen que hay que buscar otra salida."),
             ("versionDebil", "Porque sí, porque lo prometiste",
              "Tienen razones: la confianza y lo que la hermana organizó.")],
            "Lo que importa es el mejor resultado",
            [voice("e2_l_v1", "Perspectiva de quien creció con promesas incumplidas",
                   "Eso no es lo que pienso: esa idea es del otro lado.",
                   "Casi. Falta lo que más me importa.",
                   "Sí: yo recuerdo quién fue y quién no.",
                   "Muy fuerte: entendiste por qué no es solo un sábado."),
             voice("e2_l_v2", "Perspectiva de una madre",
                   "No me representa.",
                   "Parcialmente. Falta decir qué concluimos.",
                   "Así lo diría: ella contaba contigo.",
                   "Lo dijiste mejor que yo, y respondiste a la deuda."),
             voice("e2_l_v3", "Perspectiva de quien trabaja con niños",
                   "Eso no es lo que pienso.",
                   "Hay algo, pero falta por qué aplica aquí.",
                   "Sí, así lo diría: a esa edad una promesa pesa mucho.",
                   "Especialmente fuerte. Así es.")]),
        "right": side("e2_r",
            ["Las promesas existen para servir a las personas",
             "Un deber puede pesar y aun así ceder ante otro mayor"],
            ["La deuda también la afecta a ella", "Se puede explicar, pedir perdón y reparar"],
            "Es legítimo romperla, explicándolo y reparando",
            [(["e2_r_palabra"], "La palabra pesa, nadie lo niega. Pero pesar no es lo mismo que decidir: otras cosas también pesan."),
             (["e2_r_hermana"], "Ella cuenta contigo, sí; también cuenta con que la familia esté bien.")],
            "Una promesa rota se puede reparar; una deuda urgente, a veces no.",
            [("malaIntencion", "Las promesas no valen nada",
              "Sí valen: por eso hablan de explicar y reparar."),
             ("exageracion", "Si te conviene, rompe cualquier promesa",
              "No es cualquier conveniencia: es una necesidad de toda la familia."),
             ("versionDebil", "Es solo una presentación de danza",
              "No lo minimizan: reconocen que duele y proponen reparar.")],
            "Una promesa se cumple aunque cueste",
            [voice("e2_r_v1", "Perspectiva de quien sostiene a su familia con dos trabajos",
                   "Eso no es lo que pienso.",
                   "Vas bien, pero falta lo que más me importa.",
                   "Sí: a veces no hay otra salida.",
                   "Muy fuerte: entendiste que no es falta de cariño."),
             voice("e2_r_v2", "Perspectiva de quien pidió perdón y reparó",
                   "No me representa.",
                   "Parcialmente. Falta por qué aplica aquí.",
                   "Así lo diría: se explica y se repara.",
                   "Lo dijiste mejor que yo."),
             voice("e2_r_v3", "Perspectiva de una hermana mayor",
                   "Eso no es lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí, así lo diría.",
                   "Especialmente fuerte: respondiste a lo que el otro lado diría.")]),
    },
    "twist": {"text": "Una variante antes de volver a decidir.", "probe": "e2_secreto"},
    "reflection": "¿Una promesa te obliga por lo que le pasa a la otra persona, o por lo que tú dijiste?",
    "map": [{"axis": "ax_limites_resultado", "source": "stance", "polarity": 1},
            {"axis": "ax_intencion_resultado", "source": "probe", "probe": "e2_secreto", "key": "choice",
             "values": {"falle": -2, "cambia": 2, "nose": 0}}],
    "deepDive": {
        "problem": "¿Qué crea una promesa? Si solo importaran los resultados, romperla sería correcto cada vez que conviene. Si obligara siempre, nunca podría ceder ante una necesidad mayor.",
        "positions": ["La promesa crea una obligación propia, basada en la confianza de quien espera.",
                      "La promesa pesa, pero puede ceder ante deberes más urgentes si se explica y se repara."],
        "traditions": "W. D. Ross habló de deberes que pesan de antemano y pueden ceder ante otros. Hume entendió las promesas como una convención social útil. T. M. Scanlon las explica por lo que le debemos a quien confió en nosotros.",
        "objection": "Si una promesa puede ceder siempre que algo pese más, ¿qué queda de su fuerza especial?",
        "references": ["ref_ross_1930", "ref_hume_tratado", "ref_scanlon_1998", "ref_sep_promises"],
    },
}

# ---------------------------------------------------------------- E3
e3 = {
    "id": E3, "order": 3, "tramo": 1,
    "title": "Lo que viste",
    "question": "¿Debemos tratar siempre a todos de la misma manera?",
    "sensitive": False,
    "scenario": {"layout": "single", "paragraphs": [
        "Ves a tu hermano rayar un auto al estacionar e irse sin dejar sus datos.",
        "Al día siguiente, el dueño, un taxista del barrio al que no conoces, pregunta si alguien vio algo.",
        "Tu hermano te dice: «Prométeme que no dirás nada. Yo lo arreglo después»."]},
    "probes": [{
        "id": "e3_anillos", "type": "proximityRings", "placement": "vuelve",
        "prompt": "¿Y si no hubiera sido tu hermano?",
        "config": {"rings": [{"id": "companero", "label": "Un compañero de trabajo"},
                             {"id": "desconocido", "label": "Un desconocido"}],
                   "choices": [{"value": -1, "label": "Callaría"}, {"value": 0, "label": "No lo sé"},
                               {"value": 1, "label": "Se lo contaría al dueño"}]},
    }],
    "judgment": {"prompt": "¿Qué harías?",
                 "left": {"label": "Callar y exigirle que repare", "short": "Callar"},
                 "right": {"label": "Contarle al dueño lo que vi", "short": "Contarlo"}},
    "reasons": [
        reason("e3_r_familia", "Con la familia es distinto", ["p_cercanos"], "left"),
        reason("e3_r_reparar", "Lo importante es que el daño se repare", ["p_mejor_resultado"], "left"),
        reason("e3_r_mismo_trato", "El dueño tiene los mismos derechos que mi hermano", ["p_imparcial"], "right"),
        reason("e3_r_encubrir", "Encubrir también le hace daño a mi hermano", ["p_imparcial"], "right"),
    ],
    "triggers": [
        trig("e3_t_mem_callar", 1, "memory", "e3_q_mem_callar",
             all_(leaf("e2_promesa_sabado.reason.id", "eq", "e2_r_palabra"),
                  leaf("this.stance.initial", "lt", 0)), memory=E2),
        trig("e3_t_mem_contar", 2, "memory", "e3_q_mem_contar",
             all_(leaf("e2_promesa_sabado.reason.id", "eq", "e2_r_palabra"),
                  leaf("this.stance.initial", "gt", 0)), memory=E2),
        trig("e3_t_familia", 10, "assumption", "e3_q_familia",
             all_(leaf("this.stance.initial", "lt", 0), leaf("this.reason.id", "eq", "e3_r_familia"))),
        trig("e3_t_madre", 11, "internal", "e3_q_madre", leaf("this.stance.initial", "gt", 0)),
        trig("e3_t_reparar", 12, "assumption", "e3_q_reparar", leaf("this.stance.initial", "lt", 0)),
        trig("e3_t_centro", 13, "internal", "e3_q_centro", leaf("this.stance.initial", "eq", 0)),
    ],
    "questions": [
        tension("e3_q_mem_callar",
                "En «{titulo}» elegiste «{razon}». Tu hermano te pidió prometer silencio. ¿Obliga igual una promesa de ocultar algo?",
                "Entonces, una promesa obliga aunque sirva para ocultar un daño a otro. ¿Lo aceptas?"),
        tension("e3_q_mem_contar",
                "En «{titulo}» elegiste «{razon}». Aquí contarías, aunque tu hermano te pidió una promesa. Hay algo interesante aquí.",
                "Entonces, la palabra dada no obliga cuando se pidió para ocultar algo. ¿Lo aceptas?"),
        assumption("e3_q_familia",
                   "Tu razón supone que cuidar a la familia incluye protegerla de las consecuencias de sus actos. ¿Lo crees?"),
        clarification("e3_q_madre", "Si hubiera sido tu madre, ¿también se lo contarías al dueño?",
                      [ans("si", "Sí, también", axis="ax_mios_todos", value=1),
                       ans("no", "No, con ella sería distinto", "e3_q_madre_b", axis="ax_mios_todos", value=-1),
                       ans("nose", "No lo sé")]),
        tension("e3_q_madre_b",
                "Con tu hermano lo contarías; con tu madre, no. Hay algo interesante aquí.",
                "Entonces, cuánto quieres a alguien cambia lo que le debes a un desconocido. ¿Lo aceptas?"),
        assumption("e3_q_reparar",
                   "Tu razón supone que tu hermano realmente reparará el daño si callas. ¿Lo crees?"),
        clarification("e3_q_centro", "¿Qué te ayudaría a decidir?",
                      [ans("hablar", "Hablar primero con mi hermano"),
                       ans("dano", "Saber cuánto le cuesta al taxista"),
                       ans("nada", "Nada: los dos lados pesan igual")]),
    ],
    "differences": [
        diff("e3_dif_especiales", "A los nuestros les debemos cosas que no debemos a todos", "d05_nuestros_todos",
             "Si esa diferencia importa, con un desconocido que rayó el auto tu decisión podría ser otra. ¿Lo sostienes?"),
        diff("e3_dif_proteger", "Proteger a alguien no es lo mismo que ocultar el daño", "d05_nuestros_todos",
             "Si esa diferencia importa, puedes proteger a tu hermano y aun así asegurar que el taxista sepa lo que pasó. ¿Lo sostienes?"),
        diff("e3_dif_promesa", "Una promesa para ocultar algo no obliga igual", "d03_deber_que_pesa",
             "Si esa diferencia importa, la promesa pesa, pero no decide en este caso. ¿Lo sostienes?"),
    ],
    "cruza": {
        "left": side("e3_l",
            ["Las relaciones cercanas crean deberes especiales",
             "Tratar a un hermano como a un extraño destruye algo valioso"],
            ["Es un daño material y tu hermano puede repararlo", "Puedes protegerlo y exigirle que se haga cargo"],
            "Callar, pero asegurar que repare el daño",
            [(["e3_r_mismo_trato"], "El dueño tiene derechos, y se respetan si el daño se repara, sin que tú delates a tu hermano."),
             (["e3_r_encubrir"], "No es encubrir si le exiges que lo arregle; es darle la oportunidad de hacerlo bien.")],
            "La lealtad no pide ocultar el daño: pide cuidar a quien lo causó mientras lo repara.",
            [("malaIntencion", "Solo quieren salvar a los suyos",
              "No es salvarlo: le exigen que repare."),
             ("exageracion", "A la familia se la protege haga lo que haga",
              "No es cualquier cosa: es un daño que se puede reparar."),
             ("versionDebil", "Es solo un rayón",
              "No lo minimizan: quieren que se repare, sin romper el vínculo.")],
            "Todos merecen el mismo trato",
            [voice("e3_l_v1", "Perspectiva de quien cuida a sus hermanos menores",
                   "Eso no es lo que pienso: esa idea es del otro lado.",
                   "Vas bien, pero falta lo que más me importa.",
                   "Sí: a un hermano no lo entregas, lo haces responder.",
                   "Lo dijiste mejor que yo."),
             voice("e3_l_v2", "Perspectiva de quien viene de una familia muy unida",
                   "No me representa.",
                   "Parcialmente. Falta por qué aplica aquí.",
                   "Así lo diría.",
                   "Especialmente fuerte: respondiste a tu propia razón."),
             voice("e3_l_v3", "Perspectiva de quien cometió un error de joven",
                   "Eso no es lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí: a mí me dieron la oportunidad de reparar.",
                   "Así mismo.")]),
        "right": side("e3_r",
            ["Si las reglas solo valen para los extraños, no son reglas",
             "La lealtad no incluye ocultar un daño a otra persona"],
            ["El taxista vive de su auto y no sabe quién lo dañó", "Tu hermano se fue sin dejar sus datos"],
            "Contarle al dueño lo que viste",
            [(["e3_r_familia"], "Con la familia es distinto, sí: por eso importa que tu hermano aprenda a responder."),
             (["e3_r_reparar"], "Que se repare depende de que el dueño sepa a quién pedírselo.")],
            "Decir la verdad también es una forma de cuidar a tu hermano.",
            [("malaIntencion", "Quieren castigar al hermano",
              "No buscan castigo: buscan que el daño no quede oculto."),
             ("exageracion", "Hay que denunciar a la familia por cualquier cosa",
              "No es cualquier cosa: hay un tercero perjudicado que no sabe nada."),
             ("versionDebil", "Las reglas son las reglas",
              "Tienen una razón concreta: el taxista necesita saber qué pasó.")],
            "Con la familia es distinto",
            [voice("e3_r_v1", "Perspectiva de quien trabaja como conductor",
                   "Eso no es lo que pienso.",
                   "Algo hay, pero falta lo que más me importa.",
                   "Sí: ese auto es su trabajo.",
                   "Especialmente fuerte. Así es."),
             voice("e3_r_v2", "Perspectiva de quien nunca recibió reparación por un daño",
                   "No me representa.",
                   "Parcialmente. Falta decir qué concluimos.",
                   "Así lo diría: el que calla también decide.",
                   "Lo dijiste mejor que yo."),
             voice("e3_r_v3", "Perspectiva de quien tuvo que contar algo de un familiar",
                   "Eso no es lo que pienso.",
                   "Casi. Falta por qué aplica aquí.",
                   "Sí: no fue fácil, pero era justo.",
                   "Muy fuerte: entendiste que también fue cuidar.")]),
    },
    "twist": {"text": "Antes de volver a decidir, cambia a la persona que rayó el auto.", "probe": "e3_anillos"},
    "reflection": "¿Tratar a todos por igual es justicia, o hay cosas que solo les debemos a los nuestros?",
    "map": [{"axis": "ax_mios_todos", "source": "stance", "polarity": 1, "context": "cercanos"},
            {"axis": "ax_mios_todos", "source": "probe", "probe": "e3_anillos", "key": "desconocido",
             "values": {"-1": -2, "0": 0, "1": 2}, "context": "desconocidos"}],
    "deepDive": {
        "problem": "¿Debemos tratar a todos por igual, o hay deberes especiales con quienes queremos? La pregunta aparece en tradiciones muy distintas.",
        "positions": ["Las relaciones cercanas crean deberes especiales que la imparcialidad no puede borrar.",
                      "La justicia exige aplicar las mismas reglas a todos, también a los nuestros."],
        "traditions": "En el Eutifrón de Platón, un hijo acusa a su padre. En las Analectas (13.18) y en el Mencio (7A35) se valora proteger a la familia. William Godwin defendió una imparcialidad estricta. Bernard Williams criticó exigirla en las relaciones personales. La ética del cuidado de Nel Noddings pone los vínculos en el centro.",
        "objection": "Si los deberes especiales pesan tanto, la lealtad puede convertirse en complicidad con una injusticia.",
        "references": ["ref_platon_eutifron", "ref_analectas", "ref_mencio", "ref_godwin_1793", "ref_williams_pcm",
                       "ref_noddings_1984"],
    },
}

EXPERIENCES = [e1, e2, e3]
