from common import *

E1 = "e1_mismo_descuido"
E2 = "e2_promesa_sabado"
E7 = "e7_la_carta"
E8 = "e8_la_copia"
E9 = "e9_sin_haberlo_vivido"

# ---------------------------------------------------------------- E7
e7 = {
    "id": E7, "order": 7, "tramo": 3,
    "title": "La carta",
    "question": "¿Comprender es solo responder bien?",
    "sensitive": False,
    "scenario": {"layout": "single", "paragraphs": [
        "Un amigo acaba de perder a Luna, la perra que lo acompañó once años.",
        "Recibe una carta de consuelo. Léela: no sabes quién la escribió."]},
    "probes": [{
        "id": "e7_carta", "type": "annotatedLetter", "placement": "elige",
        "prompt": "Toca las frases que te suenan a comprensión.",
        "config": {"phrases": [
            "Supe lo de Luna y quise escribirte.",
            "Once años es mucho tiempo para compartir una casa.",
            "Me acuerdo de cómo te esperaba en la puerta cada tarde.",
            "No hay palabras que llenen ese silencio.",
            "Está bien si hoy no quieres hablar con nadie.",
            "Lo que sientes tiene el tamaño del cariño que le tuviste.",
            "Cuando quieras, cuéntame una historia de ella.",
            "Aquí estoy."],
            "reveal": "Esta carta la escribió un sistema automático a partir de unos pocos datos: el nombre de la perra, los años que vivieron juntos y un recuerdo."},
    }],
    "judgment": {"prompt": "¿La carta comprendía lo que tu amigo estaba viviendo?",
                 "left": {"label": "No comprendía: usó bien las palabras", "short": "No comprendía"},
                 "right": {"label": "Comprendía, a su manera", "short": "Comprendía"}},
    "reasons": [
        reason("e7_r_interior", "Comprender requiere sentir o querer decir algo", ["p_interior"], "left"),
        reason("e7_r_reglas", "Seguir reglas no es entender", ["p_interior"], "left"),
        reason("e7_r_conducta", "A las personas también las juzgamos por lo que hacen", ["p_conducta"], "right"),
        reason("e7_r_efecto", "Consoló de verdad, y eso cuenta", ["p_conducta"], "right"),
    ],
    "triggers": [
        trig("e7_t_mem_piezas", 1, "memory", "e7_q_mem_piezas", leaf("hollow.count", "gte", 1), memory="hollow"),
        trig("e7_t_saber", 10, "internal", "e7_q_saber", leaf("this.stance.initial", "lt", 0)),
        trig("e7_t_loro", 11, "internal", "e7_q_loro", leaf("this.stance.initial", "gt", 0)),
        trig("e7_t_centro", 12, "internal", "e7_q_centro", leaf("this.stance.initial", "eq", 0)),
    ],
    "questions": [
        clarification("e7_q_mem_piezas",
                      "Hasta ahora reconstruiste {n} posiciones con piezas. ¿Las comprendiste, o acomodaste bien las piezas?",
                      [ans("comprendi", "Las comprendí", "e7_q_piezas_a", leaf("this.stance.initial", "lt", 0)),
                       ans("acomode", "Acomodé bien las piezas", "e7_q_piezas_b", leaf("this.stance.initial", "gt", 0)),
                       ans("nose", "No sé distinguirlo")]),
        tension("e7_q_piezas_a",
                "Dijiste que usar bien las palabras no es comprender. Tú también usaste bien unas piezas. ¿Qué te hace distinto de la carta?",
                "Entonces, a ti y a la carta los juzgas con criterios distintos. ¿Lo aceptas?"),
        tension("e7_q_piezas_b",
                "Dijiste que la carta comprendía por lo que hizo. Tú acomodaste bien las piezas. Hay algo interesante aquí.",
                "Entonces, acomodar bien las piezas ya sería comprender. ¿Lo aceptas?"),
        clarification("e7_q_saber", "Tu razón supone que puedes saber si otra persona siente algo. ¿Cómo lo sabes?",
                      [ans("hace", "Por lo que hace y dice", "e7_q_conducta"),
                       ans("siento", "Porque yo también siento"),
                       ans("nose", "No lo sé con certeza")]),
        tension("e7_q_conducta",
                "Si a las personas les atribuyes comprensión por lo que hacen y dicen, la carta también hizo y dijo. Hay algo interesante aquí.",
                "Entonces, a una persona y a la carta las juzgas con criterios distintos. ¿Lo aceptas?"),
        clarification("e7_q_loro", "Si un loro repitiera esas mismas frases, ¿también comprendería?",
                      [ans("si", "Sí, también"),
                       ans("no", "No", "e7_q_loro_b"),
                       ans("nose", "No lo sé")]),
        tension("e7_q_loro_b",
                "Dijiste que la carta comprendía, pero que un loro que dice lo mismo no. Hay algo interesante aquí.",
                "Entonces, no basta con decir lo correcto: importa cómo se llegó a decirlo. ¿Lo aceptas?"),
        clarification("e7_q_centro", "¿Qué necesitarías saber para decidir?",
                      [ans("como", "Cómo se escribió exactamente"),
                       ans("amigo", "Qué sintió mi amigo al leerla"),
                       ans("nada", "Nada: no creo que se pueda saber")]),
    ],
    "differences": [
        diff("e7_dif_significado", "Yo sé lo que significan; la carta no", "d10_usar_entender",
             "Si esa diferencia importa, podrías usar palabras que no entiendes y la carta podría no entender las suyas. ¿Lo sostienes?"),
        diff("e7_dif_vivido", "Algo de lo que reconstruí lo he vivido", "d12_saber_vivido",
             "Si esa diferencia importa, comprender depende de haber vivido algo parecido. ¿Lo sostienes?"),
        diff("e7_dif_intencion", "Yo quise entender; la carta no quiso nada", "d10_usar_entender",
             "Si esa diferencia importa, sin intención no hay comprensión, aunque el resultado sea el mismo. ¿Lo sostienes?"),
    ],
    "cruza": {
        "left": side("e7_l",
            ["Seguir reglas sobre palabras no produce significado",
             "Comprender es entender lo que se dice, no solo decirlo bien"],
            ["La carta no sabe qué es perder a un perro", "Nadie quiso decir nada al escribirla"],
            "La carta no comprendía, aunque consolara",
            [(["e7_r_conducta"], "A las personas las juzgamos por lo que hacen porque sabemos que también sienten; con la carta no lo sabemos."),
             (["e7_r_efecto"], "Consoló, sí. Un poema también consuela y no te conoce.")],
            "Que algo consuele no prueba que comprenda.",
            [("malaIntencion", "Odian la tecnología",
              "No es rechazo a la tecnología: es una pregunta sobre qué es comprender."),
             ("exageracion", "Una máquina nunca podrá hacer nada humano",
              "No dicen nunca: dicen que esta carta no comprendía."),
             ("versionDebil", "Es una máquina y punto",
              "Tienen una razón: sin significado, no hay comprensión.")],
            "Comprender es responder bien",
            [voice("e7_l_v1", "Perspectiva de quien escribe cartas a mano",
                   "Eso no es lo que pienso: esa idea es del otro lado.",
                   "Vas bien, pero falta lo que más me importa.",
                   "Sí: una carta dice algo porque alguien quiso decirlo.",
                   "Lo dijiste mejor que yo."),
             voice("e7_l_v2", "Perspectiva de quien trabaja con el lenguaje",
                   "No me representa.",
                   "Parcialmente. Falta por qué aplica aquí.",
                   "Así lo diría: forma no es significado.",
                   "Especialmente fuerte: respondiste a tu propia razón."),
             voice("e7_l_v3", "Perspectiva de quien perdió a su mascota",
                   "Eso no es lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí: me consoló, pero no me conocía.",
                   "Muy fuerte.")]),
        "right": side("e7_r",
            ["A otros les atribuimos comprensión por lo que hacen, no porque veamos dentro",
             "Exigirle más a una máquina que a una persona es un doble estándar"],
            ["Respondió justo a lo que tu amigo necesitaba", "Usó el nombre y un recuerdo en el momento justo"],
            "La carta comprendía, a su manera",
            [(["e7_r_interior"], "¿Cómo sabes que otra persona siente algo? Lo sabes por lo que hace."),
             (["e7_r_reglas"], "Nuestro cerebro también funciona siguiendo procesos; eso no nos impide comprender.")],
            "Si comprender se ve en lo que alguien hace, la carta hizo lo que haría alguien que comprende.",
            [("malaIntencion", "Quieren reemplazar a las personas",
              "No buscan reemplazar a nadie: preguntan qué criterio usamos para decir que alguien comprende."),
             ("exageracion", "Las máquinas ya son personas",
              "No dicen eso: dicen que esta carta comprendía a su manera."),
             ("versionDebil", "Si funciona, da igual",
              "Tienen una razón: juzgamos la comprensión por la conducta.")],
            "Comprender requiere sentir algo",
            [voice("e7_r_v1", "Perspectiva de quien programa sistemas de texto",
                   "Eso no es lo que pienso.",
                   "Algo hay, pero falta lo que más me importa.",
                   "Sí: la comprensión se ve en la respuesta.",
                   "Especialmente fuerte. Así es."),
             voice("e7_r_v2", "Perspectiva de quien recibió consuelo de un desconocido",
                   "No me representa.",
                   "Parcialmente. Falta decir qué concluimos.",
                   "Así lo diría: me comprendió sin conocerme.",
                   "Lo dijiste mejor que yo."),
             voice("e7_r_v3", "Perspectiva de quien estudia cómo aprendemos",
                   "Eso no es lo que pienso.",
                   "Casi. Falta por qué aplica aquí.",
                   "Sí: comprender también es saber usar.",
                   "Muy fuerte.")]),
    },
    "twist": {"text": "¿Y si la hubiera escrito una persona copiando frases de un manual de condolencias? ¿Cambia algo?"},
    "reflection": "¿Cómo sabes que alguien te comprende?",
    "map": [],
    "openQuestion": True,
    "deepDive": {
        "problem": "¿Comprender es responder bien, o hace falta algo más, como entender lo que se dice o querer decirlo?",
        "positions": ["Manejar símbolos con acierto no basta: comprender requiere significado.",
                      "Atribuimos comprensión por la conducta; exigir más a una máquina sería un doble estándar."],
        "traditions": "Alan Turing propuso juzgar la inteligencia por la conducta (1950). John Searle respondió con el argumento de la habitación china (1980). Daniel Dennett defendió atribuir estados mentales cuando eso ayuda a entender y predecir. Emily Bender y Alexander Koller distinguieron la forma del significado en los sistemas de lenguaje.",
        "objection": "Si solo vemos la conducta de los demás, nos falta un criterio claro para negar comprensión a una máquina y concedérsela a una persona.",
        "references": ["ref_turing_1950", "ref_searle_1980", "ref_dennett_1987", "ref_bender_koller_2020",
                       "ref_sep_chinese_room"],
    },
}

# ---------------------------------------------------------------- E8
e8 = {
    "id": E8, "order": 8, "tramo": 3,
    "title": "La copia",
    "question": "¿Seguirías siendo tú si todos tus recuerdos fueran copiados?",
    "sensitive": True,
    "sensitiveNote": "Esta pregunta imagina un accidente grave y la muerte de una persona.",
    "scenario": {"layout": "single", "paragraphs": [
        "En el futuro, tras un accidente grave, un servicio médico puede crear una persona con todos tus recuerdos, tu carácter y tus proyectos, en un cuerpo sano.",
        "Tu cuerpo original no sobrevive."]},
    "probes": [{
        "id": "e8_gradiente", "type": "replacementGradient", "placement": "elige",
        "prompt": "Antes: si tu cuerpo se reemplazara poco a poco, conservando tus recuerdos, ¿en qué punto dejarías de ser tú?",
        "config": {"min": 10, "max": 100, "step": 10, "never": "Nunca dejaría de ser yo"},
    }],
    "judgment": {"prompt": "La persona con tus recuerdos, ¿serías tú?",
                 "left": {"label": "La copia no sería yo", "short": "No sería yo"},
                 "right": {"label": "La copia sería yo", "short": "Sería yo"}},
    "reasons": [
        reason("e8_r_cuerpo", "Soy también este cuerpo", ["p_continuidad_fisica"], "left"),
        reason("e8_r_hilo", "Algo tiene que continuar sin corte", ["p_continuidad_fisica"], "left"),
        reason("e8_r_memoria", "Soy mis recuerdos, mi carácter, mis proyectos", ["p_continuidad_psicologica"], "right"),
        reason("e8_r_importa", "Da igual si soy yo: importa que siga lo que me importa",
               ["p_continuidad_psicologica"], "right"),
    ],
    "triggers": [
        trig("e8_t_mem_promesa", 1, "memory", "e8_q_mem_promesa",
             leaf("e2_promesa_sabado.status", "eq", "completed"), memory=E2),
        trig("e8_t_mem_responsable", 2, "memory", "e8_q_mem_responsable",
             all_(leaf("e1_mismo_descuido.status", "eq", "completed"),
                  leaf("e2_promesa_sabado.status", "ne", "completed")), memory=E1),
        trig("e8_t_gradiente", 5, "internal", "e8_q_gradiente",
             all_(leaf("this.probe.e8_gradiente.stop", "lt", 100), leaf("this.stance.initial", "gt", 0))),
        trig("e8_t_corte", 10, "assumption", "e8_q_corte", leaf("this.stance.initial", "lt", 0)),
        trig("e8_t_todo", 11, "assumption", "e8_q_todo", leaf("this.stance.initial", "gt", 0)),
        trig("e8_t_centro", 12, "internal", "e8_q_centro", leaf("this.stance.initial", "eq", 0)),
    ],
    "questions": [
        clarification("e8_q_mem_promesa",
                      "En «{titulo}» elegiste «{postura}». Si tu copia recuerda esa promesa, ¿debería cumplirla?",
                      [ans("si", "Sí: es su promesa", "e8_q_promesa_a", leaf("this.stance.initial", "lt", 0)),
                       ans("no", "No: ella no la hizo", "e8_q_promesa_b", leaf("this.stance.initial", "gt", 0)),
                       ans("nose", "No lo sé")]),
        tension("e8_q_promesa_a",
                "Dijiste que la copia no sería tú, pero que debería cumplir tu promesa. Hay algo interesante aquí.",
                "Entonces, alguien que no es tú podría heredar tus promesas. ¿Lo aceptas?"),
        tension("e8_q_promesa_b",
                "Dijiste que la copia sería tú, pero que no debería cumplir tu promesa. Hay algo interesante aquí.",
                "Entonces, ser la misma persona no basta para heredar lo prometido. ¿Lo aceptas?"),
        clarification("e8_q_mem_responsable",
                      "En «{titulo}» elegiste «{postura}». Si tu copia recordara haber hecho algo así, ¿sería responsable de ello?",
                      [ans("si", "Sí: recuerda haberlo hecho"),
                       ans("no", "No: ella no lo hizo"),
                       ans("nose", "No lo sé")]),
        tension("e8_q_gradiente",
                "Dijiste que dejarías de ser tú al reemplazar el {fact:this.probe.e8_gradiente.stop} % de tu cuerpo, aunque conservaras tus recuerdos, pero que la copia sería tú. Hay algo interesante aquí.",
                "Entonces, para ti el cuerpo importa poco a poco, pero no de golpe. ¿Lo aceptas?"),
        assumption("e8_q_corte",
                   "Tu razón supone que algo tiene que continuar sin interrupción para que sigas siendo tú. ¿Lo crees?"),
        assumption("e8_q_todo", "Tu razón supone que tus recuerdos y tu carácter son todo lo que eres. ¿Lo crees?"),
        clarification("e8_q_centro", "¿Qué te haría inclinarte?",
                      [ans("amigos", "Saber si mis amigos la reconocerían"),
                       ans("sentir", "Saber si ella sentiría ser yo"),
                       ans("nada", "Nada: no creo que tenga respuesta")]),
    ],
    "differences": [
        diff("e8_dif_importa", "Quizás no importa si es yo, sino que siga lo que me importa", "d11_seguir_conservar",
             "Si esa diferencia importa, podrías aceptar la copia aunque no fuera exactamente tú. ¿Lo sostienes?"),
        diff("e8_dif_recordar", "Recordar algo no es haberlo hecho", None,
             "Si esa diferencia importa, la copia recordaría tu vida sin haberla vivido. ¿Lo sostienes?"),
        diff("e8_dif_dos", "Si hay dos, ninguno es solo yo", "d11_seguir_conservar",
             "Si esa diferencia importa, la identidad no puede duplicarse, aunque los recuerdos sí. ¿Lo sostienes?"),
    ],
    "cruza": {
        "left": side("e8_l",
            ["Una persona no puede estar en dos lugares a la vez", "Soy un organismo, no solo información"],
            ["Si el original sobreviviera, habría dos personas", "La copia empieza a existir el día que la crean"],
            "La copia sería otra persona, muy parecida a mí",
            [(["e8_r_memoria"], "Tus recuerdos estarían en ella, sí; pero recordar algo no es haberlo vivido."),
             (["e8_r_importa"], "Que siga lo que te importa no significa que sigas tú.")],
            "Una copia perfecta sigue siendo una copia.",
            [("malaIntencion", "Tienen miedo a la tecnología",
              "No es miedo: es una pregunta sobre qué nos hace ser quienes somos."),
             ("exageracion", "Si te cambian una sola célula ya no eres tú",
              "No dicen eso: dicen que una copia nueva es otra persona."),
             ("versionDebil", "Es una copia, se nota",
              "Tienen una razón: una persona no puede estar en dos lugares.")],
            "Soy mis recuerdos",
            [voice("e8_l_v1", "Perspectiva de quien cree que somos nuestro cuerpo",
                   "Eso no es lo que pienso: esa idea es del otro lado.",
                   "Vas bien, pero falta lo que más me importa.",
                   "Sí: yo soy este cuerpo que vive.",
                   "Lo dijiste mejor que yo."),
             voice("e8_l_v2", "Perspectiva de quien cuidó a una persona con pérdida de memoria",
                   "No me representa.",
                   "Parcialmente. Falta por qué aplica aquí.",
                   "Así lo diría: seguía siendo ella aunque no recordara.",
                   "Especialmente fuerte: respondiste a tu propia razón."),
             voice("e8_l_v3", "Perspectiva de quien estudia biología",
                   "Eso no es lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí, así lo diría.",
                   "Muy fuerte.")]),
        "right": side("e8_r",
            ["Lo que me hace ser yo es mi memoria, mi carácter y mis proyectos",
             "Mi cuerpo cambia todo el tiempo y sigo siendo yo"],
            ["La copia tendría todo eso, sin que le falte nada", "Mis amigos la reconocerían"],
            "La copia sería yo",
            [(["e8_r_cuerpo"], "Tu cuerpo ya cambió muchísimo desde que eras niño, y sigues siendo tú."),
             (["e8_r_hilo"], "Cuando duermes profundamente también hay una pausa, y despiertas siendo tú.")],
            "Si nada de lo que te importa se pierde, lo que continúa eres tú.",
            [("malaIntencion", "Quieren vender inmortalidad",
              "No venden nada: preguntan qué nos hace ser quienes somos."),
             ("exageracion", "Una foto tuya también eres tú",
              "No es una foto: es alguien con tus recuerdos y tu carácter."),
             ("versionDebil", "Si se parece, es lo mismo",
              "No es parecido: es continuidad de memoria y carácter.")],
            "Soy también este cuerpo",
            [voice("e8_r_v1", "Perspectiva de quien se reinventó por completo",
                   "Eso no es lo que pienso.",
                   "Algo hay, pero falta lo que más me importa.",
                   "Sí: cambié todo y sigo siendo yo.",
                   "Especialmente fuerte. Así es."),
             voice("e8_r_v2", "Perspectiva de quien valora sus recuerdos por encima de todo",
                   "No me representa.",
                   "Parcialmente. Falta decir qué concluimos.",
                   "Así lo diría.",
                   "Lo dijiste mejor que yo."),
             voice("e8_r_v3", "Perspectiva de quien trabaja con tecnología",
                   "Eso no es lo que pienso.",
                   "Casi. Falta por qué aplica aquí.",
                   "Sí: lo que importa es el patrón, no el material.",
                   "Muy fuerte.")]),
    },
    "twist": {"text": "Ahora imagina que tu cuerpo original también sobrevive. Hay dos personas con tus recuerdos. ¿Cambia algo?"},
    "reflection": "Si mañana no fueras exactamente quien eres hoy, ¿qué tendría que conservarse para que siguiera importándote?",
    "map": [],
    "openQuestion": True,
    "deepDive": {
        "problem": "¿Qué nos hace ser la misma persona a lo largo del tiempo: el cuerpo, la memoria, el carácter, o algo más?",
        "positions": ["La identidad personal depende de la continuidad psicológica: memoria, carácter y proyectos.",
                      "Somos organismos: una copia, por perfecta que sea, sería otra persona."],
        "traditions": "John Locke ligó la identidad personal a la conciencia y la memoria, y llamó a la persona un término relacionado con la responsabilidad. Thomas Reid le objetó casos de memoria interrumpida. Bernard Williams mostró cómo cambian nuestras intuiciones según cómo se cuente el caso. Derek Parfit sostuvo que la identidad no es lo que importa. Eric Olson defendió que somos animales. En el Milindapañha, el carro de Nāgasena cuestiona que exista un yo aparte de sus partes.",
        "objection": "Si la memoria define la identidad, la duplicación produciría dos personas que serían la misma, y eso parece imposible.",
        "references": ["ref_locke_ensayo", "ref_reid_1785", "ref_williams_1970", "ref_parfit_1984",
                       "ref_olson_1997", "ref_milindapanha"],
    },
}

# ---------------------------------------------------------------- E9
e9 = {
    "id": E9, "order": 9, "tramo": 3,
    "title": "Sin haberlo vivido",
    "question": "¿Puedes comprender una posición sin haberla vivido?",
    "sensitive": False,
    "scenario": {"layout": "single", "paragraphs": [
        "Una amiga migró sola a otro país hace años y ahora está decidiendo si volver.",
        "Cuando le das tu opinión, te responde: «No puedes entenderlo; no lo viviste»."]},
    "probes": [{
        "id": "e9_formas", "type": "knowingForms", "placement": "vuelve",
        "prompt": "Mira las posiciones que reconstruiste. ¿Qué comprendiste de cada una?",
        "config": {"options": [{"id": "que", "label": "Qué piensan"},
                               {"id": "porque", "label": "Por qué lo piensan"},
                               {"id": "siente", "label": "Cómo se siente pensarlo"}]},
    }],
    "judgment": {"prompt": "¿Tiene razón tu amiga?",
                 "left": {"label": "No puedo entenderlo sin haberlo vivido", "short": "No puedo"},
                 "right": {"label": "Puedo entender sus razones sin haberlo vivido", "short": "Sí puedo"}},
    "reasons": [
        reason("e9_r_sentir", "Hay cosas que solo se saben sintiéndolas", ["p_experiencia_vivida"], "left"),
        reason("e9_r_escuchar", "Lo que me toca es escucharla, no opinar", ["p_experiencia_vivida"], "left"),
        reason("e9_r_razones", "Las razones se pueden compartir", ["p_razones_compartibles"], "right"),
        reason("e9_r_imaginar", "Escuchar e imaginar también enseñan", ["p_razones_compartibles"], "right"),
    ],
    "triggers": [
        trig("e9_t_mem_onb_tension", 1, "memory", "e9_q_mem_onb_tension",
             any_(all_(leaf("onboarding.stance", "gt", 0), leaf("this.stance.initial", "lt", 0)),
                  all_(leaf("onboarding.stance", "lt", 0), leaf("this.stance.initial", "gt", 0))),
             memory="onboarding"),
        trig("e9_t_mem_hollow", 2, "memory", "e9_q_mem_hollow", leaf("hollow.count", "gte", 1), memory="hollow"),
        trig("e9_t_mem_onb", 3, "memory", "e9_q_mem_onb", leaf("onboarding.stance", "exists"), memory="onboarding"),
        trig("e9_t_sentir", 10, "assumption", "e9_q_sentir", leaf("this.stance.initial", "lt", 0)),
        trig("e9_t_opinar", 11, "assumption", "e9_q_opinar", leaf("this.stance.initial", "gt", 0)),
        trig("e9_t_centro", 12, "internal", "e9_q_centro", leaf("this.stance.initial", "eq", 0)),
    ],
    "questions": [
        tension("e9_q_mem_onb_tension",
                "Al empezar respondiste «{postura}» ({seguridad}) a «¿Se puede entender a alguien sin darle la razón?». Ahora elegiste «{esta_postura}». Hay algo interesante aquí.",
                "Entonces, entender a alguien sin darle la razón no es lo mismo que entender lo que vivió. ¿Lo aceptas?"),
        clarification("e9_q_mem_hollow",
                      "En este recorrido reconstruiste {n} posiciones, y {k} fueron reconocidas como justas. ¿Eso es comprender?",
                      [ans("si", "Sí, es una forma de comprender"),
                       ans("no", "No del todo: faltaría haberlo vivido", "e9_q_hollow_b",
                           leaf("this.stance.initial", "gt", 0)),
                       ans("nose", "No lo sé")]),
        tension("e9_q_hollow_b",
                "Dijiste que puedes entender sus razones sin haberlo vivido, pero que reconstruir no es comprender del todo. Hay algo interesante aquí.",
                "Entonces, entender razones y comprender a alguien son cosas distintas. ¿Lo aceptas?"),
        clarification("e9_q_mem_onb",
                      "Al empezar respondiste «{postura}» ({seguridad}) a «¿Se puede entender a alguien sin darle la razón?». ¿Lo sigues pensando?",
                      [ans("si", "Sí, lo sigo pensando"),
                       ans("matiz", "Ahora lo matizaría"),
                       ans("nose", "No lo sé")]),
        assumption("e9_q_sentir", "Tu razón supone que las razones de tu amiga dependen de lo que sintió. ¿Lo crees?"),
        assumption("e9_q_opinar", "Tu razón supone que entender sus razones basta para opinar sobre su decisión. ¿Lo crees?"),
        clarification("e9_q_centro", "¿Qué te haría inclinarte?",
                      [ans("escuchar", "Escucharla más tiempo"),
                       ans("vivir", "Haber vivido algo parecido"),
                       ans("nada", "Nada: las dos cosas pesan igual")]),
    ],
    "differences": [
        diff("e9_dif_saber_sentir", "Entender sus razones no es saber cómo se siente", "d12_saber_vivido",
             "Si esa diferencia importa, puedes entender por qué decide sin saber cómo se siente decidirlo. ¿Lo sostienes?"),
        diff("e9_dif_decidir", "Puedo entender, y aun así no me toca decidir", None,
             "Si esa diferencia importa, comprender no te da derecho a decidir por ella. ¿Lo sostienes?"),
    ],
    "cruza": {
        "left": side("e9_l",
            ["Hay un saber que solo da la experiencia",
             "No escuchar a quien lo vivió es no tomarla en serio"],
            ["Ella vivió años sola en otro país", "Tus razones pueden ser correctas y aun así no saber cuánto pesan"],
            "Solo quien lo vivió lo entiende del todo",
            [(["e9_r_razones"], "Sus razones se pueden compartir; lo que pesan, no."),
             (["e9_r_imaginar"], "Imaginar ayuda, pero puede hacerte creer que ya sabes.")],
            "Entender de lejos no es lo mismo que entender de cerca.",
            [("malaIntencion", "Solo quieren callar a los demás",
              "No buscan callar a nadie: piden escuchar primero."),
             ("exageracion", "Nadie puede entender a nadie",
              "No dicen eso: dicen que hay algo que solo da la experiencia."),
             ("versionDebil", "Si no lo viviste, no opines",
              "Tienen una razón: el peso de lo vivido.")],
            "Las razones se pueden compartir",
            [voice("e9_l_v1", "Perspectiva de quien migró sola",
                   "Eso no es lo que pienso: esa idea es del otro lado.",
                   "Vas bien, pero falta lo que más me importa.",
                   "Sí: hay noches que no se explican.",
                   "Lo dijiste mejor que yo."),
             voice("e9_l_v2", "Perspectiva de quien regresó a su país",
                   "No me representa.",
                   "Parcialmente. Falta por qué aplica aquí.",
                   "Así lo diría.",
                   "Especialmente fuerte: respondiste a tu propia razón."),
             voice("e9_l_v3", "Perspectiva de quien vivió una pérdida",
                   "Eso no es lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí: me explicaron mucho, pero no era lo mismo.",
                   "Muy fuerte.")]),
        "right": side("e9_r",
            ["Si nadie pudiera entender sin vivirlo, ningún desacuerdo se resolvería",
             "Escuchar, preguntar e imaginar permiten comprender razones"],
            ["Puedes conocer sus motivos sin sentir lo mismo", "Muchas personas la acompañaron sin haber migrado"],
            "Se pueden entender sus razones, aunque no se sienta lo mismo",
            [(["e9_r_sentir"], "Es cierto: no sabrás cómo se siente. Pero puedes entender por qué decide lo que decide."),
             (["e9_r_escuchar"], "Escuchar es justamente el camino para entender.")],
            "Comprender razones no exige haberlas vivido; exige escucharlas bien.",
            [("malaIntencion", "Quieren opinar de todo",
              "No es opinar de todo: es poder entender a otros."),
             ("exageracion", "Leer un artículo es lo mismo que vivirlo",
              "No dicen que sea lo mismo: dicen que las razones se pueden comprender."),
             ("versionDebil", "Todo se puede entender",
              "Tienen una razón: sin comprensión entre vidas distintas, no habría diálogo.")],
            "Hay cosas que solo se saben sintiéndolas",
            [voice("e9_r_v1", "Perspectiva de quien escribe historias de otras personas",
                   "Eso no es lo que pienso.",
                   "Algo hay, pero falta lo que más me importa.",
                   "Sí: escuchar bien también es una forma de saber.",
                   "Especialmente fuerte. Así es."),
             voice("e9_r_v2", "Perspectiva de quien acompañó a una amiga migrante",
                   "No me representa.",
                   "Parcialmente. Falta decir qué concluimos.",
                   "Así lo diría.",
                   "Lo dijiste mejor que yo."),
             voice("e9_r_v3", "Perspectiva de quien enseña a escuchar",
                   "Eso no es lo que pienso.",
                   "Casi. Falta por qué aplica aquí.",
                   "Sí: comprender empieza por preguntar.",
                   "Muy fuerte.")]),
    },
    "twist": {"text": "Antes de volver a decidir, mira lo que reconstruiste en este recorrido.", "probe": "e9_formas"},
    "reflection": "Comprender a alguien, ¿se termina alguna vez?",
    "map": [],
    "openQuestion": True,
    "deepDive": {
        "problem": "¿Hace falta haber vivido algo para comprenderlo? ¿O las razones de otra persona pueden comprenderse sin sentir lo mismo?",
        "positions": ["Hay un saber que solo da la experiencia, y no escucharlo es no tomar en serio a quien lo vivió.",
                      "Las razones se pueden comprender a través del testimonio, la narración y la imaginación."],
        "traditions": "Bertrand Russell distinguió el conocimiento por familiaridad del conocimiento por descripción. Thomas Nagel y Frank Jackson defendieron que algo de la experiencia no se capta desde fuera. L. A. Paul lo aplicó a las decisiones que nos transforman. Miranda Fricker estudió cómo se desoye el testimonio de algunas personas. Martha Nussbaum defendió que la literatura ayuda a comprender vidas ajenas.",
        "objection": "Si nadie puede comprender lo que no vivió, no habría forma de resolver desacuerdos entre personas con vidas distintas.",
        "references": ["ref_russell_1911", "ref_nagel_1974", "ref_jackson_1982", "ref_paul_2014", "ref_fricker_2007",
                       "ref_nussbaum_1995"],
    },
}

EXPERIENCES = [e7, e8, e9]
