from common import *

E1 = "e1_mismo_descuido"
E2 = "e2_promesa_sabado"
E3 = "e3_lo_que_viste"
E4 = "e4_verdad_incomoda"
E5 = "e5_cien_becas"
E6 = "e6_donde_estas"

# Conjunto de datos de Cien becas (verificado por fuerza bruta: ningún par de
# umbrales cumple los dos criterios a la vez con tolerancia de 3 puntos).
_SCORES = [5, 15, 25, 35, 45, 55, 65, 75, 85, 95]
_NORTE = [6, 13, 14, 18, 20, 22, 23, 24, 32, 39]
_SUR = [39, 29, 28, 24, 24, 18, 17, 13, 13, 6]


def _bins(counts):
    out = []
    for s, n in zip(_SCORES, counts):
        pos = int(n * s / 100 + 0.5)  # redondeo hacia arriba en .5, explícito
        out.append({"score": s, "n": n, "pos": pos})
    return out


FAIRNESS_CONFIG = {
    "groups": [{"id": "norte", "label": "Barrio Norte", "bins": _bins(_NORTE)},
               {"id": "sur", "label": "Barrio Sur", "bins": _bins(_SUR)}],
    "tolerance": 0.03,
    "indicator1": "Una beca predice lo mismo en ambos barrios",
    "indicator1Help": "Entre quienes reciben beca, la proporción que termina sus estudios es casi igual en los dos barrios.",
    "indicator2": "Los errores se reparten igual",
    "indicator2Help": "Las becas negadas por error y las dadas por error ocurren en proporciones casi iguales en los dos barrios.",
    "reveal": "No es un fallo del diseño. Se ha demostrado matemáticamente que, cuando los grupos tienen tasas distintas y la predicción no es perfecta, estos dos criterios no se pueden cumplir a la vez.",
}

# ---------------------------------------------------------------- E4
e4 = {
    "id": E4, "order": 4, "tramo": 2,
    "title": "La verdad incómoda",
    "question": "¿Mentir puede ser lo correcto?",
    "sensitive": True,
    "sensitiveNote": "Una de las variantes menciona a alguien que busca hacerle daño a otra persona.",
    "scenario": {"layout": "single", "paragraphs": [
        "Tu mejor amiga invirtió sus ahorros en un pequeño negocio de comida. Está ilusionada y pasa por un momento difícil.",
        "Antes de firmar un préstamo para ampliarlo, te pide tu opinión sincera. Tienes buenas razones para creer que el negocio va a fracasar."]},
    "probes": [{
        "id": "e4_escalera", "type": "ladder", "placement": "vuelve",
        "prompt": "¿Desde qué peldaño mentir te parecería aceptable?",
        "config": {"rungs": [
            "Opinar sobre un regalo que no te gustó",
            "El negocio de tu amiga",
            "Tu jefe pregunta si un compañero llegó tarde, y decirlo le costaría el puesto",
            "Alguien llega a tu puerta buscando a tu amigo para hacerle daño"],
            "never": "Nunca: no mentiría en ninguno"},
    }],
    "judgment": {"prompt": "¿Qué le dirías?",
                 "left": {"label": "Decirle la verdad, con cuidado", "short": "La verdad"},
                 "right": {"label": "Suavizarla hasta no decirla", "short": "Suavizarla"}},
    "reasons": [
        reason("e4_r_derecho", "Ella tiene derecho a decidir con toda la información", ["p_autonomia"], "left",
               "ax_decidir_proteger", -1),
        reason("e4_r_confianza", "Si le miento, ¿para qué me pregunta?", ["p_verdad"], "left"),
        reason("e4_r_proteger", "Ahora necesita ánimo, no un golpe", ["p_proteccion"], "right",
               "ax_decidir_proteger", 1),
        reason("e4_r_amiga", "Una amiga merece que la cuide", ["p_cercanos"], "right", "ax_mios_todos", -1),
    ],
    "triggers": [
        trig("e4_t_mem_palabra", 1, "memory", "e4_q_mem_palabra",
             all_(leaf("e2_promesa_sabado.reason.id", "eq", "e2_r_palabra"),
                  leaf("this.stance.initial", "gt", 0)), memory=E2),
        trig("e4_t_mem_callar", 2, "memory", "e4_q_mem_callar",
             all_(leaf("e3_lo_que_viste.stance.final", "lt", 0), leaf("this.stance.initial", "lt", 0)),
             memory=E3),
        trig("e4_t_dano", 10, "assumption", "e4_q_dano", leaf("this.stance.initial", "gt", 0)),
        trig("e4_t_cuidado", 11, "assumption", "e4_q_cuidado", leaf("this.stance.initial", "lt", 0)),
        trig("e4_t_centro", 12, "internal", "e4_q_centro", leaf("this.stance.initial", "eq", 0)),
    ],
    "questions": [
        tension("e4_q_mem_palabra",
                "En «{titulo}» elegiste «{razon}». Aquí suavizarías la verdad. ¿Tu palabra es un límite y la verdad no?",
                "Entonces, cumplir tu palabra y decir la verdad pesan distinto para ti. ¿Lo aceptas?"),
        tension("e4_q_mem_callar",
                "En «{titulo}» elegiste «{postura}». Aquí eliges decir la verdad. Hay algo interesante aquí.",
                "Entonces, callar ante un desconocido y hablar con una amiga pueden ser coherentes. ¿Lo aceptas?"),
        assumption("e4_q_dano",
                   "Tu razón supone que la verdad le haría más daño que el fracaso del negocio. ¿Lo crees?",
                   "e4_q_dano_b"),
        tension("e4_q_dano_b",
                "Si el fracaso le haría más daño que la verdad, suavizarla podría dejarla sola ante ese fracaso. ¿Cómo lo ves?",
                "Entonces, protegerla hoy puede costarle más mañana. ¿Lo aceptas?"),
        assumption("e4_q_cuidado",
                   "Tu razón supone que siempre hay una forma cuidadosa de decir la verdad. ¿Lo crees?"),
        clarification("e4_q_centro", "¿Qué te haría inclinarte?",
                      [ans("seguridad", "Estar más seguro de que fracasará"),
                       ans("momento", "Que ella estuviera en un mejor momento"),
                       ans("nada", "Nada: las dos cosas pesan igual")]),
    ],
    "differences": [
        diff("e4_dif_no_decir", "No decirlo todo no es lo mismo que mentir", "d06_mentir_no_decir",
             "Si esa diferencia importa, podrías callar parte de lo que piensas sin decir nada falso. ¿Lo sostienes?"),
        diff("e4_dif_umbral", "Depende de cuánto esté en juego", "d07_linea_fija_movil",
             "Si esa diferencia importa, con un riesgo más grave tu respuesta podría cambiar. ¿Lo sostienes?"),
        diff("e4_dif_amistad", "Con una amiga, el deber es cuidarla", "d05_nuestros_todos",
             "Si esa diferencia importa, a un desconocido le dirías la verdad sin suavizarla. ¿Lo sostienes?"),
    ],
    "cruza": {
        "left": side("e4_l",
            ["Mentir es decidir por el otro qué puede saber",
             "La confianza entre amigas depende de no mentirse"],
            ["Va a firmar un préstamo: la decisión es suya y es grande",
             "Hay formas cuidadosas de decir la verdad"],
            "Decirle lo que piensas, con cuidado",
            [(["e4_r_proteger"], "Necesita ánimo, sí: también para decidir bien antes de firmar."),
             (["e4_r_amiga"], "Cuidarla incluye no dejarla firmar a ciegas.")],
            "La verdad dicha con cuidado también es una forma de cariño.",
            [("malaIntencion", "Les gusta tener razón",
              "No se trata de tener razón: se trata de su decisión."),
             ("exageracion", "La verdad siempre, aunque destruya a alguien",
              "Proponen decirla con cuidado, no con crueldad."),
             ("versionDebil", "Mentir está mal y punto",
              "Tienen razones: su derecho a decidir y la confianza.")],
            "Protegerla ahora es lo más importante",
            [voice("e4_l_v1", "Perspectiva de quien perdió dinero sin que nadie le advirtiera",
                   "Eso no es lo que pienso: esa idea es del otro lado.",
                   "Vas bien, pero falta lo que más me importa.",
                   "Sí: yo habría querido saberlo.",
                   "Lo dijiste mejor que yo."),
             voice("e4_l_v2", "Perspectiva de quien emprendió",
                   "No me representa.",
                   "Parcialmente. Falta por qué aplica aquí.",
                   "Así lo diría: la decisión era mía.",
                   "Especialmente fuerte: respondiste a tu propia razón."),
             voice("e4_l_v3", "Perspectiva de quien valora la franqueza",
                   "Eso no es lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí, así lo diría.",
                   "Muy fuerte, y dicho con cuidado.")]),
        "right": side("e4_r",
            ["La verdad es un valor entre otros, no el único",
             "La amistad también incluye cuidar"],
            ["Pasa por un momento difícil", "Tu opinión también puede estar equivocada"],
            "Suavizar tu opinión y acompañarla",
            [(["e4_r_derecho"], "Decidirá igual: tu opinión es una opinión, no un dato."),
             (["e4_r_confianza"], "Te pregunta para sentirse acompañada, no para recibir un veredicto.")],
            "A veces lo que alguien necesita no es un pronóstico, sino compañía.",
            [("malaIntencion", "Prefieren quedar bien que ser honestos",
              "No buscan quedar bien: buscan no dañarla en un mal momento."),
             ("exageracion", "Mentir está bien si alguien se siente mejor",
              "No es cualquier mentira: es este momento y esta amiga."),
             ("versionDebil", "Una mentirita no hace daño",
              "Reconocen que pesa: por eso hablan de acompañarla.")],
            "Ella tiene derecho a decidir con toda la información",
            [voice("e4_r_v1", "Perspectiva de quien emprendió y fracasó",
                   "Eso no es lo que pienso.",
                   "Algo hay, pero falta lo que más me importa.",
                   "Sí: en ese momento necesitaba ánimo.",
                   "Especialmente fuerte. Así es."),
             voice("e4_r_v2", "Perspectiva de quien acompañó a una amiga en crisis",
                   "No me representa.",
                   "Parcialmente. Falta decir qué concluimos.",
                   "Así lo diría.",
                   "Lo dijiste mejor que yo."),
             voice("e4_r_v3", "Perspectiva de quien cuida a otros en momentos difíciles",
                   "Eso no es lo que pienso.",
                   "Casi. Falta por qué aplica aquí.",
                   "Sí: primero se sostiene a la persona.",
                   "Muy fuerte: entendiste que no es falta de respeto.")]),
    },
    "twist": {"text": "Antes de volver a decidir, mira otros casos.", "probe": "e4_escalera"},
    "reflection": "¿Hay una línea que no cruzarías, o tu línea se mueve según lo que está en juego?",
    "map": [{"axis": "ax_limites_resultado", "source": "stance", "polarity": 1},
            {"axis": "ax_limites_resultado", "source": "probe", "probe": "e4_escalera", "key": "line",
             "values": {"0": -3, "4": -1, "3": 0, "2": 1, "1": 2}}],
    "deepDive": {
        "problem": "¿La prohibición de mentir es absoluta, depende de un umbral o depende de las consecuencias?",
        "positions": ["Mentir decide por el otro qué puede saber y daña la confianza de todas las palabras.",
                      "La verdad es un valor importante, pero no el único: a veces cuidar pesa más."],
        "traditions": "Agustín de Hipona rechazó toda mentira. Kant sostuvo que no se debe mentir ni siquiera a quien busca hacer daño, en su respuesta a Benjamin Constant. Christine Korsgaard reexaminó ese caso. Sissela Bok, Bernard Williams y Jennifer Saul estudiaron la mentira y el engaño en la vida cotidiana.",
        "objection": "Si la línea contra la mentira se mueve con lo que está en juego, cuesta distinguirla de un simple cálculo de consecuencias.",
        "references": ["ref_agustin_mendacio", "ref_kant_1797", "ref_korsgaard_1986", "ref_bok_1978",
                       "ref_williams_2002", "ref_saul_2012", "ref_sep_deontology"],
    },
}

# ---------------------------------------------------------------- E5
_mem_answers = lambda cond_res, cond_int: [
    ans("resultados", "Sí: aquí importan los resultados", "e5_q_mem_tension", cond_res,
        axis="ax_intencion_resultado", value=2),
    ans("intencion", "No: sin intención no hay injusticia", "e5_q_mem_tension", cond_int,
        axis="ax_intencion_resultado", value=-2),
    ans("diseno", "La responsabilidad es de quien lo diseñó"),
]
_E1_DECIDE = leaf("e1_mismo_descuido.reason.id", "in", ["e1_r_decision", "e1_r_riesgo"])
_E1_RESULT = leaf("e1_mismo_descuido.reason.id", "in", ["e1_r_resultado", "e1_r_victima"])

e5 = {
    "id": E5, "order": 5, "tramo": 2,
    "title": "Cien becas",
    "question": "¿Qué hace justa una decisión automática?",
    "sensitive": False,
    "scenario": {"layout": "single", "paragraphs": [
        "Tu municipio repartirá unas cien becas con un sistema que predice quién terminará sus estudios.",
        "En el barrio Norte, históricamente termina sus estudios más gente que en el barrio Sur. Te piden ajustar el sistema."]},
    "probes": [{
        "id": "e5_simulador", "type": "fairnessSimulator", "placement": "elige",
        "prompt": "Ajusta el puntaje mínimo para recibir beca en cada barrio.",
        "config": FAIRNESS_CONFIG,
    }],
    "judgment": {"prompt": "¿Qué debería importar más?",
                 "left": {"label": "Que una beca signifique lo mismo en ambos barrios", "short": "Mismo significado"},
                 "right": {"label": "Que los errores se repartan igual", "short": "Errores parejos"}},
    "reasons": [
        reason("e5_r_individuo", "Cada persona debe medirse con el mismo criterio", ["p_mismo_criterio"], "left"),
        reason("e5_r_confiable", "Si el puntaje cambia de sentido, nadie puede confiar en él", ["p_mismo_criterio"], "left"),
        reason("e5_r_historia", "Los errores no deben caer más sobre quien ya tenía desventaja",
               ["p_errores_repartidos"], "right"),
        reason("e5_r_costo", "Lo que importa es quién paga los errores", ["p_errores_repartidos"], "right"),
        reason("e5_r_reglas", "Ninguna: cambiaría las reglas del sistema", [], "both"),
    ],
    "triggers": [
        trig("e5_t_mem_decision", 1, "memory", "e5_q_mem_decision",
             leaf("e1_mismo_descuido.reason.id", "eq", "e1_r_decision"), memory=E1),
        trig("e5_t_mem_resultado", 2, "memory", "e5_q_mem_resultado", _E1_RESULT, memory=E1),
        trig("e5_t_mem_riesgo", 3, "memory", "e5_q_mem_riesgo",
             leaf("e1_mismo_descuido.reason.id", "eq", "e1_r_riesgo"), memory=E1),
        trig("e5_t_mem_postura", 4, "memory", "e5_q_mem_postura",
             leaf("e1_mismo_descuido.status", "eq", "completed"), memory=E1),
        trig("e5_t_mismo", 10, "twin", "e5_q_mismo", leaf("this.stance.initial", "lt", 0)),
        trig("e5_t_ajuste", 11, "twin", "e5_q_ajuste", leaf("this.stance.initial", "gt", 0)),
        trig("e5_t_centro", 12, "internal", "e5_q_centro", leaf("this.stance.initial", "eq", 0)),
    ],
    "questions": [
        clarification("e5_q_mem_decision",
                      "En «{titulo}» elegiste «{razon}». Este sistema no decide ni quiere nada, y sus resultados son desiguales. ¿Puede ser injusto?",
                      _mem_answers(_E1_DECIDE, _E1_RESULT)),
        clarification("e5_q_mem_resultado",
                      "En «{titulo}» elegiste «{razon}». Aquí los resultados son desiguales entre barrios. ¿Eso basta para decir que el sistema es injusto?",
                      _mem_answers(_E1_DECIDE, _E1_RESULT)),
        clarification("e5_q_mem_riesgo",
                      "En «{titulo}» elegiste «{razon}». Aquí, ¿quién asume el riesgo de los errores del sistema?",
                      [ans("postulantes", "Quienes quedan fuera por error", axis="ax_intencion_resultado", value=1),
                       ans("nadie", "Nadie en particular: es un sistema", axis="ax_intencion_resultado", value=-1),
                       ans("quien", "Quien decidió usarlo")]),
        clarification("e5_q_mem_postura",
                      "En «{titulo}» elegiste «{postura}» ({seguridad}). Este sistema no tiene intenciones, pero sus resultados no son iguales. ¿Cómo lo ves?",
                      [ans("resultados", "Aquí importan los resultados", axis="ax_intencion_resultado", value=2),
                       ans("intencion", "Sin intención no hay injusticia", axis="ax_intencion_resultado", value=-2),
                       ans("diseno", "La responsabilidad es de quien lo diseñó")]),
        tension("e5_q_mem_tension",
                "En «{titulo}» elegiste «{razon}». Aquí respondiste «{respuesta}». Hay algo interesante aquí.",
                "Entonces, juzgar a una persona y evaluar un sistema siguen reglas distintas. ¿Lo aceptas?"),
        tension("e5_q_mismo",
                "Con el mismo significado del puntaje, en el barrio Sur quedan sin beca más personas que sí habrían terminado. ¿Cómo lo ves?",
                "Entonces, un criterio igual para cada persona puede producir cargas desiguales entre barrios. ¿Lo aceptas?"),
        tension("e5_q_ajuste",
                "Si ajustas el umbral por barrio, una misma beca significará cosas distintas según dónde vivas. ¿Cómo lo ves?",
                "Entonces, tratar distinto a cada barrio puede ser la forma de ser justo. ¿Lo aceptas?"),
        clarification("e5_q_centro", "¿Qué te haría inclinarte?",
                      [ans("historia", "Saber de dónde vienen las diferencias entre barrios"),
                       ans("personas", "Conocer a quienes quedan fuera"),
                       ans("nada", "Nada: los dos criterios pesan igual")]),
    ],
    "differences": [
        diff("e5_dif_puntaje_errores",
             "Que la beca signifique lo mismo y que los errores se repartan igual son cosas distintas",
             "d08_puntaje_errores",
             "Si esa diferencia importa, alguien tiene que decidir cuál sacrificar, porque no se pueden tener ambas. ¿Lo sostienes?"),
        diff("e5_dif_personas_sistemas", "Juzgar a una persona no es lo mismo que evaluar un sistema", None,
             "Si esa diferencia importa, un sistema puede ser injusto aunque nadie haya querido hacer daño. ¿Lo sostienes?"),
        diff("e5_dif_reglas", "El problema no es el umbral, sino las reglas del sistema", None,
             "Si esa diferencia importa, ajustar números no basta: habría que cambiar cómo se reparten las becas. ¿Lo sostienes?"),
    ],
    "cruza": {
        "left": side("e5_l",
            ["Ser justo es aplicar el mismo criterio a cada persona",
             "Una puntuación debe significar lo mismo para todos"],
            ["Con umbrales distintos, dos personas iguales reciben trato distinto por su barrio",
             "Si el puntaje cambia de sentido, nadie puede confiar en él"],
            "Mantener el mismo significado del puntaje en ambos barrios",
            [(["e5_r_historia"], "La desventaja es real, y se corrige mejor con apoyo antes de postular que torciendo la medida."),
             (["e5_r_costo"], "Un criterio que cambia según el barrio también tiene un costo, y lo paga la confianza.")],
            "Medir igual a todos no resuelve todo, pero evita que el lugar decida por la persona.",
            [("malaIntencion", "No les importa el barrio Sur",
              "Les importa: proponen apoyo antes de postular."),
             ("exageracion", "Las matemáticas nunca se equivocan",
              "No dicen que el sistema sea perfecto: dicen que el criterio debe ser el mismo."),
             ("versionDebil", "Los números son los números",
              "Tienen una razón: un mismo criterio para cada persona.")],
            "Los errores deben repartirse igual",
            [voice("e5_l_v1", "Perspectiva de quien diseña sistemas de evaluación",
                   "Eso no es lo que pienso: esa idea es del otro lado.",
                   "Vas bien, pero falta lo que más me importa.",
                   "Sí: un puntaje tiene que significar lo mismo.",
                   "Lo dijiste mejor que yo."),
             voice("e5_l_v2", "Perspectiva de quien estudió de noche en el barrio Norte",
                   "No me representa.",
                   "Parcialmente. Falta por qué aplica aquí.",
                   "Así lo diría: no quiero que mi barrio decida por mí.",
                   "Especialmente fuerte: respondiste a tu propia razón."),
             voice("e5_l_v3", "Perspectiva de quien confía en las reglas claras",
                   "Eso no es lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí, así lo diría.",
                   "Muy fuerte.")]),
        "right": side("e5_r",
            ["Nadie debe cargar más con los errores por el lugar donde vive",
             "Un sistema también responde por sus efectos"],
            ["En el barrio Sur quedan fuera más personas que sí habrían terminado",
             "La diferencia entre barrios viene de desventajas pasadas"],
            "Ajustar el sistema para que los errores se repartan igual",
            [(["e5_r_individuo"], "Medir con el mismo criterio suena justo, pero si el criterio arrastra el pasado, repite la desventaja."),
             (["e5_r_confiable"], "La confianza también se pierde si un barrio siempre sale perdiendo.")],
            "Un sistema justo no es el que mide igual, sino el que no reparte peor los errores.",
            [("malaIntencion", "Quieren quitarle becas al Norte",
              "No es quitar: es no repartir peor los errores."),
             ("exageracion", "Hay que ignorar el mérito",
              "No ignoran el mérito: dicen que medirlo tiene errores y que esos errores no deben caer siempre en el mismo lugar."),
             ("versionDebil", "Que sea parejo y ya",
              "Tienen una razón precisa: quién carga con los errores.")],
            "Cada persona debe medirse con el mismo criterio",
            [voice("e5_r_v1", "Perspectiva de quien vive en el barrio Sur",
                   "Eso no es lo que pienso.",
                   "Algo hay, pero falta lo que más me importa.",
                   "Sí: los errores siempre caen de este lado.",
                   "Especialmente fuerte. Así es."),
             voice("e5_r_v2", "Perspectiva de quien trabajó en programas de becas",
                   "No me representa.",
                   "Parcialmente. Falta decir qué concluimos.",
                   "Así lo diría.",
                   "Lo dijiste mejor que yo."),
             voice("e5_r_v3", "Perspectiva de quien se quedó fuera por un error",
                   "Eso no es lo que pienso.",
                   "Casi. Falta por qué aplica aquí.",
                   "Sí: detrás de cada error hay una persona.",
                   "Muy fuerte: entendiste a quién le toca perder.")]),
    },
    "twist": {"text": "Imagina que no sabes en qué barrio vivirás. ¿Qué regla elegirías?"},
    "reflection": "Si dos ideas razonables de justicia no pueden cumplirse a la vez, ¿quién debería decidir cuál tiene prioridad?",
    "map": [],
    "deepDive": {
        "problem": "¿Qué hace justa una decisión automática? Cuando los grupos tienen tasas distintas y la predicción no es perfecta, criterios razonables de justicia entran en conflicto.",
        "positions": ["Ser justo es medir a cada persona con el mismo criterio: una puntuación debe significar lo mismo para todos.",
                      "Ser justo es que los errores del sistema no recaigan más sobre un grupo."],
        "traditions": "Alexandra Chouldechova (2017) y Kleinberg, Mullainathan y Raghavan (2016) mostraron que no se pueden cumplir todos los criterios a la vez. En el caso COMPAS, ProPublica y Northpointe defendieron criterios distintos. Deborah Hellman analizó cuál de ellos importa moralmente. John Rawls propuso elegir reglas sin saber qué lugar ocuparemos.",
        "objection": "Si ningún criterio puede cumplirse del todo, elegir uno es una decisión política que un número no puede tomar por nosotros.",
        "references": ["ref_chouldechova_2017", "ref_kleinberg_2016", "ref_angwin_2016", "ref_dieterich_2016",
                       "ref_hellman_2020", "ref_rawls_1971"],
    },
}

# ---------------------------------------------------------------- E6
e6 = {
    "id": E6, "order": 6, "tramo": 2,
    "title": "¿Dónde estás?",
    "question": "Si no tienes nada que ocultar, ¿importa la privacidad?",
    "sensitive": False,
    "scenario": {"layout": "single", "paragraphs": [
        "Tu familia propone que todos compartan su ubicación en tiempo real, siempre, «por seguridad».",
        "Tu hermana de 17 años no quiere. Tus padres le dicen: «Si no haces nada malo, ¿qué problema hay?»."]},
    "probes": [{
        "id": "e6_flujos", "type": "flowMatrix", "placement": "elige",
        "prompt": "¿Quién debería poder ver la ubicación de tu hermana, y cuándo? Marca lo que te parece aceptable.",
        "config": {"rows": ["Sus padres", "Sus hermanos", "Sus amigos", "La empresa de la app"],
                   "columns": ["Siempre", "Solo de noche", "Solo en emergencias"]},
    }],
    "judgment": {"prompt": "¿Qué te parece más justo?",
                 "left": {"label": "Que ella decida cuándo compartirla", "short": "Ella decide"},
                 "right": {"label": "Compartirla siempre, por seguridad", "short": "Siempre"}},
    "reasons": [
        reason("e6_r_espacio", "A los 17 necesita un espacio propio", ["p_autonomia"], "left"),
        reason("e6_r_confiar", "Confiar es no vigilarlo todo", ["p_autonomia"], "left"),
        reason("e6_r_seguridad", "Si pasa algo, hay que saber dónde está", ["p_proteccion"], "right"),
        reason("e6_r_sin_secretos", "En una familia no debería haber secretos", ["p_cercanos"], "right",
               "ax_mios_todos", -1),
    ],
    "triggers": [
        trig("e6_t_mem_derecho", 1, "memory", "e6_q_mem_derecho",
             all_(leaf("e4_verdad_incomoda.reason.id", "eq", "e4_r_derecho"),
                  leaf("this.stance.initial", "gt", 0)), memory=E4),
        trig("e6_t_contexto", 5, "internal", "e6_q_contexto",
             leaf("this.probe.e6_flujos.contextual", "eq", True)),
        trig("e6_t_mem_familia", 6, "memory", "e6_q_mem_familia",
             leaf("e3_lo_que_viste.reason.id", "eq", "e3_r_familia"), memory=E3),
        trig("e6_t_protege", 10, "assumption", "e6_q_protege", leaf("this.stance.initial", "gt", 0)),
        trig("e6_t_espacio", 11, "assumption", "e6_q_espacio", leaf("this.stance.initial", "lt", 0)),
        trig("e6_t_centro", 12, "internal", "e6_q_centro", leaf("this.stance.initial", "eq", 0)),
    ],
    "questions": [
        tension("e6_q_mem_derecho",
                "En «{titulo}» elegiste «{razon}». Aquí, ¿quién decide sobre la ubicación de tu hermana?",
                "Entonces, el derecho a decidir de tu amiga pesa más que el de tu hermana. ¿Lo aceptas?"),
        tension("e6_q_contexto",
                "Tus padres dicen «si no haces nada malo, ¿qué problema hay?». Tus elecciones en el cuadro no dependen de si algo es malo. Hay algo interesante aquí.",
                "Entonces, lo que importa es si se hace algo malo, no quién mira ni para qué. ¿Lo aceptas?"),
        clarification("e6_q_mem_familia",
                      "En «{titulo}» elegiste «{razon}». ¿También vale eso para vigilar a tu hermana?",
                      [ans("si", "Sí: con la familia hay más derecho a saber", axis="ax_decidir_proteger", value=1),
                       ans("no", "No: la familia también debe respetar su espacio", axis="ax_decidir_proteger",
                           value=-1),
                       ans("distinto", "Son cosas distintas")]),
        assumption("e6_q_protege", "Tu razón supone que saber dónde está la protege. ¿Lo crees?"),
        assumption("e6_q_espacio",
                   "Tu razón supone que compartir la ubicación le quitaría espacio propio. ¿Lo crees?"),
        clarification("e6_q_centro", "¿Qué te haría inclinarte?",
                      [ans("reciproco", "Que todos compartieran por igual"),
                       ans("edad", "Que ella fuera mayor de edad"),
                       ans("nada", "Nada: las dos cosas pesan igual")]),
    ],
    "differences": [
        diff("e6_dif_contexto", "Importa quién ve y para qué, no si es secreto", "d09_ocultar_contexto",
             "Si esa diferencia importa, compartir con sus padres en una emergencia y con una empresa siempre no son lo mismo. ¿Lo sostienes?"),
        diff("e6_dif_edad", "A los 17 no es lo mismo que a los 10", None,
             "Si esa diferencia importa, la misma regla podría ser justa para una niña y no para ella. ¿Lo sostienes?"),
        diff("e6_dif_reciproco", "Si todos se ven entre todos, es distinto", None,
             "Si esa diferencia importa, el problema no es mirar, sino que solo uno sea mirado. ¿Lo sostienes?"),
    ],
    "cruza": {
        "left": side("e6_l",
            ["La privacidad no sirve para esconder: permite ser uno mismo",
             "Confiar en alguien implica no verificarlo todo"],
            ["A los 17 está aprendiendo a decidir sola", "Sentirse observado cambia cómo actuamos"],
            "Que ella decida cuándo compartirla",
            [(["e6_r_seguridad"], "La seguridad importa: puede compartirla cuando sale de noche, sin estar vigilada siempre."),
             (["e6_r_sin_secretos"], "Tener un espacio propio no es tener secretos contra la familia.")],
            "Cuidar no exige saberlo todo en todo momento.",
            [("malaIntencion", "Quieren esconder algo",
              "No se trata de esconder: se trata de tener un espacio propio."),
             ("exageracion", "Los padres no deberían saber nada de sus hijos",
              "No dicen nada: dicen que ella decida cuándo."),
             ("versionDebil", "Es su vida y ya",
              "Tienen razones: aprender a decidir y la confianza.")],
            "Si pasa algo, hay que saber dónde está",
            [voice("e6_l_v1", "Perspectiva de quien creció muy vigilado",
                   "Eso no es lo que pienso: esa idea es del otro lado.",
                   "Vas bien, pero falta lo que más me importa.",
                   "Sí: yo no sabía quién era cuando nadie miraba.",
                   "Lo dijiste mejor que yo."),
             voice("e6_l_v2", "Perspectiva de alguien de 17 años",
                   "No me representa.",
                   "Parcialmente. Falta por qué aplica aquí.",
                   "Así lo diría.",
                   "Especialmente fuerte: respondiste a tu propia razón."),
             voice("e6_l_v3", "Perspectiva de quien trabaja con adolescentes",
                   "Eso no es lo que pienso.",
                   "Casi. Falta decir qué concluimos.",
                   "Sí: la confianza se aprende dándola.",
                   "Muy fuerte.")]),
        "right": side("e6_r",
            ["Cuidar a alguien a veces exige información",
             "En una familia, la información circula para protegerse"],
            ["Todavía es menor de edad", "Las emergencias ocurren sin aviso"],
            "Compartirla siempre, por seguridad",
            [(["e6_r_espacio"], "Puede tener su espacio: la ubicación no revela lo que piensa ni con quién habla."),
             (["e6_r_confiar"], "Si es recíproco, no es vigilancia: es cuidado mutuo.")],
            "Saber dónde está no es desconfiar: es poder llegar a tiempo.",
            [("malaIntencion", "Quieren controlarla",
              "No es control: es poder ayudar en una emergencia."),
             ("exageracion", "Hay que saberlo todo de los hijos siempre",
              "No es todo: es solo la ubicación."),
             ("versionDebil", "Por si acaso",
              "Tienen una razón concreta: que es menor y las emergencias no avisan.")],
            "Confiar es no vigilarlo todo",
            [voice("e6_r_v1", "Perspectiva de una madre que vivió un susto",
                   "Eso no es lo que pienso.",
                   "Algo hay, pero falta lo que más me importa.",
                   "Sí: esa noche no sabía dónde estaba.",
                   "Especialmente fuerte. Así es."),
             voice("e6_r_v2", "Perspectiva de quien comparte su ubicación con su pareja",
                   "No me representa.",
                   "Parcialmente. Falta decir qué concluimos.",
                   "Así lo diría: es cuidado, no control.",
                   "Lo dijiste mejor que yo."),
             voice("e6_r_v3", "Perspectiva de quien trabaja en rescate",
                   "Eso no es lo que pienso.",
                   "Casi. Falta por qué aplica aquí.",
                   "Sí: los minutos cuentan.",
                   "Muy fuerte.")]),
    },
    "twist": {"text": "Tu hermana propone compartirla solo cuando sale de noche, y que tus padres también compartan la suya. ¿Cambia algo?"},
    "reflection": "¿La privacidad protege lo que escondemos, o lo que somos cuando nadie mira?",
    "map": [{"axis": "ax_decidir_proteger", "source": "stance", "polarity": 1},
            {"axis": "ax_decidir_proteger", "source": "probe", "probe": "e6_flujos", "key": "level",
             "direct": True}],
    "deepDive": {
        "problem": "Si no tenemos nada que ocultar, ¿por qué importaría la privacidad? La pregunta supone que la privacidad solo sirve para esconder faltas.",
        "positions": ["La privacidad permite tener relaciones distintas y formarse como persona.",
                      "Cuidar a alguien vulnerable puede justificar compartir información."],
        "traditions": "James Rachels vinculó la privacidad con la posibilidad de tener relaciones distintas. Daniel Solove analizó el argumento de no tener nada que ocultar. Helen Nissenbaum propuso juzgar cada flujo de información según su contexto. John Stuart Mill y Joel Feinberg discutieron los límites del paternalismo.",
        "objection": "Si todo depende del contexto, alguien tiene que fijar las normas de cada contexto, y en una familia no siempre están de acuerdo.",
        "references": ["ref_rachels_1975", "ref_solove_2007", "ref_nissenbaum_2004", "ref_nissenbaum_2010",
                       "ref_mill_1859", "ref_feinberg_1986"],
    },
}

EXPERIENCES = [e4, e5, e6]
